A Space Story: MEntite Class Reference
MEntite Class Reference
#include <MEntite.hpp>
Public Member Functions
MEntite (std::string const &nom, std::string const &texture, MTuile *tuile=nullptr, float taille=1)
virtual ~MEntite ()
void deplacer (MTerrain &terrain, Mouvement const &deplacement)
void attaquer (MTerrain &terrain)
void seDefendre (MEntite &attaquant, int degats)
void interagirTuile (MTerrain &terrain)
void interagirEntite (MTerrain &terrain)
void utiliserObjet ()
void mine (MTerrain &terrain)
int defenseTotale () const
int forceTotale () const
void addItemToInventaire (MItem *item)
void equipe (Id idItem)
Mouvement getDirection () const
void setDirection (Mouvement direction)
std::string const & getNom () const
MTuile const * getTuile () const
void setTuile (MTuile *tuile)
float getTaille () const
void setTaille (float taille)
MCompetence const & getCompetences () const
MInventaire & getInventaire ()
void setActionDefense (std::function< void(std::string entite, int degat)> actionDefense)
void setActionInteraction (std::function< void(MEntite const &entite)> actionInteraction)
Public Member Functions inherited from MObjetTexture
MObjetTexture (std::string texture)
virtual ~MObjetTexture ()
std::string getTexture ()
void setTexture (std::string texture)
Private Member Functions
bool isAccessible (MTuile const &tuile) const
int getMiningPower ()
Private Attributes
std::string nom
MTuile * tuile
Mouvement direction
float taille
MCompetence competences
MInventaire inventaire
std::function< void(std::string entite, int degat)> actionDefense
std::function< void(MEntite const &entite)> actionInteraction
Detailed Description
Definition at line 30 of file MEntite.hpp.
Constructor & Destructor Documentation
MEntite()
MEntite::MEntite (std::string const & nom, std::string const & texture, MTuile * tuile = nullptr, float taille = 1)
Definition at line 28 of file MEntite.cpp.
References DROITE, setTaille(), and setTuile().
~MEntite()
MEntite::~MEntite () virtual
Definition at line 37 of file MEntite.cpp.
Member Function Documentation
addItemToInventaire()
void MEntite::addItemToInventaire (MItem * item)
Definition at line 182 of file MEntite.cpp.
References MInventaire::ajouterItem(), and inventaire.
Referenced by CLua::cppAddActionMining(), CLua::cppGiveNewItemToEntity(), and CLua::cppGiveNewItemToPerso().
attaquer()
void MEntite::attaquer (MTerrain & terrain)
Definition at line 158 of file MEntite.cpp.
References direction, forceTotale(), getTuile(), and seDefendre().
Referenced by CPersonnage::setEventMethods().
defenseTotale()
int MEntite::defenseTotale () const
Definition at line 177 of file MEntite.cpp.
References MInventaire::getDefenseEquipement(), and inventaire.
Referenced by seDefendre().
deplacer()
void MEntite::deplacer (MTerrain & terrain, Mouvement const & deplacement)
Deplace l'entite de deplacement sur le terrain\ eg: avec deplacement == Mouvement::HAUT,\ l'entite va se deplacer d'une case vers le haut
Parameters
terrain le terrain où se deplace l'entite
deplacement le deplacement voulu
Definition at line 52 of file MEntite.cpp.
References MTuile::deplacerEntiteVers(), ENTITY_MOVED, getDirection(), MTuile::getPosition(), isAccessible(), setDirection(), and tuile.
Referenced by CPersonnage::setEventMethods().
equipe()
void MEntite::equipe (Id idItem)
Definition at line 148 of file MEntite.cpp.
References MInventaire::equipe(), and inventaire.
forceTotale()
int MEntite::forceTotale () const
Definition at line 172 of file MEntite.cpp.
References competences, MCompetence::getForce(), MInventaire::getForceEquipement(), and inventaire.
Referenced by attaquer().
getCompetences()
MCompetence const & MEntite::getCompetences () const
Definition at line 198 of file MEntite.cpp.
References competences.
getDirection()
Mouvement MEntite::getDirection () const inline
Definition at line 108 of file MEntite.hpp.
References direction.
Referenced by CPersonnage::addRobot(), CJeu::CJeu(), deplacer(), and MRobot::isReset().
getInventaire()
MInventaire & MEntite::getInventaire ()
Definition at line 229 of file MEntite.cpp.
References inventaire.
getMiningPower()
int MEntite::getMiningPower () private
Definition at line 234 of file MEntite.cpp.
References MInventaire::estEquipe(), MInventaire::getEquipement(), MItem::getMiningLevel(), inventaire, and MAIN.
Referenced by mine().
getNom()
std::string const & MEntite::getNom () const inline
Definition at line 124 of file MEntite.hpp.
References nom.
Referenced by CPersonnage::addRobot(), CJeu::CJeu(), CLua::cppAddActionMining(), CLua::cppGetCurrentPerso(), MPartieCouche::declenchementDe(), CLua::getEntite(), MPartieCouche::passageDe(), MTuile::placeEntite(), seDefendre(), setTaille(), and MItem::utilisation().
getTaille()
float MEntite::getTaille () const inline
Definition at line 134 of file MEntite.hpp.
References taille.
Referenced by MTuile::deplacerEntiteVers().
getTuile()
MTuile const * MEntite::getTuile () const inline
Definition at line 129 of file MEntite.hpp.
References tuile.
Referenced by attaquer(), CJeu::CJeu(), interagirEntite(), and MRobot::isReset().
interagirEntite()
void MEntite::interagirEntite (MTerrain & terrain)
Definition at line 116 of file MEntite.cpp.
References actionInteraction, direction, getTuile(), and MThreads::parallelize().
Referenced by CPersonnage::setEventMethods().
interagirTuile()
void MEntite::interagirTuile (MTerrain & terrain)
interagi avec la tuile dans la direction de l'entité\ ex: appuie sur un bouton
Parameters
terrain le terrain ou est l'entité
Definition at line 105 of file MEntite.cpp.
References direction, MTuile::getPosition(), MTuile::interagirTuile(), and tuile.
Referenced by CPersonnage::setEventMethods().
isAccessible()
bool MEntite::isAccessible (MTuile const & tuile) const private
Definition at line 153 of file MEntite.cpp.
References MTuile::isAdjacente().
Referenced by deplacer().
mine()
void MEntite::mine (MTerrain & terrain)
mine la MTuile devant l'entite (la couche 1 : MTypeCouche::ELEMENT)
Parameters
terrain le terrain ou est l'entité
Definition at line 137 of file MEntite.cpp.
References direction, getMiningPower(), MTuile::getPosition(), MTuile::mine(), and tuile.
Referenced by CPersonnage::setEventMethods().
seDefendre()
void MEntite::seDefendre (MEntite & attaquant, int degats)
Definition at line 91 of file MEntite.cpp.
References actionDefense, competences, defenseTotale(), MCompetence::enleveVie(), getNom(), and MThreads::parallelize().
Referenced by attaquer().
setActionDefense()
void MEntite::setActionDefense (std::function< void(std::string entite, int degat)> actionDefense) inline
Definition at line 113 of file MEntite.hpp.
References actionDefense.
Referenced by CLua::cppAddActionDefense().
setActionInteraction()
void MEntite::setActionInteraction (std::function< void(MEntite const &entite)> actionInteraction) inline
Definition at line 118 of file MEntite.hpp.
References actionInteraction.
Referenced by CPersonnage::addRobot().
setDirection()
void MEntite::setDirection (Mouvement direction)
Definition at line 203 of file MEntite.cpp.
References direction, and ENTITY_MOVED.
Referenced by deplacer(), and MRobot::reset().
setTaille()
void MEntite::setTaille (float taille) inline
Definition at line 139 of file MEntite.hpp.
References getNom(), taille, and to_string().
Referenced by CLua::cppSetTaille(), and MEntite().
setTuile()
void MEntite::setTuile (MTuile * tuile)
Definition at line 213 of file MEntite.cpp.
References MTuile::deplacerEntiteVers(), MTuile::placeEntite(), and tuile.
Referenced by CLua::cppSetPosition(), MEntite(), and MRobot::reset().
utiliserObjet()
void MEntite::utiliserObjet ()
Definition at line 187 of file MEntite.cpp.
References MInventaire::getEquipement(), inventaire, MAIN, and MItem::utilisation().
Referenced by CPersonnage::setEventMethods().
Member Data Documentation
actionDefense
std::function<void(std::string entite, int degat)> MEntite::actionDefense private
Definition at line 51 of file MEntite.hpp.
Referenced by seDefendre(), and setActionDefense().
actionInteraction
std::function<void(MEntite const& entite)> MEntite::actionInteraction private
Definition at line 52 of file MEntite.hpp.
Referenced by interagirEntite(), and setActionInteraction().
competences
MCompetence MEntite::competences private
Definition at line 48 of file MEntite.hpp.
Referenced by forceTotale(), getCompetences(), and seDefendre().
direction
Mouvement MEntite::direction private
en degrée, 0 : en haut (0), 90 : droite (1) 180 : bas (2) -90 : gauche (3)
Definition at line 43 of file MEntite.hpp.
Referenced by attaquer(), getDirection(), interagirEntite(), interagirTuile(), mine(), and setDirection().
inventaire
MInventaire MEntite::inventaire private
Definition at line 49 of file MEntite.hpp.
Referenced by addItemToInventaire(), defenseTotale(), equipe(), forceTotale(), getInventaire(), getMiningPower(), and utiliserObjet().
nom
std::string MEntite::nom private
Definition at line 34 of file MEntite.hpp.
Referenced by getNom().
taille
float MEntite::taille private
allant de 0 à 1 pour savoir quel pourcentage d'une tuile prend une entité
Definition at line 47 of file MEntite.hpp.
Referenced by getTaille(), and setTaille().
tuile
MTuile* MEntite::tuile private
Definition at line 35 of file MEntite.hpp.
Referenced by deplacer(), getTuile(), interagirTuile(), mine(), and setTuile().
The documentation for this class was generated from the following files:
src/model/MEntite.hpp
src/model/MEntite.cpp