A Space Story: CJeu Class Reference
CJeu Class Reference
#include <CJeu.hpp>
Public Member Functions
CJeu ()
virtual ~CJeu ()
MEntite * getEntite (std::string name)
MPersonnage * getPersonnage (std::string name)
Private Attributes
AppFrameInterface * vuePrincipale
CNiveau cNiveau
CPersonnage cPersonnage
CLua cLua
std::future< void > thread
Friends
class CLua
Detailed Description
Controller for controllers
Definition at line 24 of file CJeu.hpp.
Constructor & Destructor Documentation
CJeu()
CJeu::CJeu ()
Definition at line 31 of file CJeu.cpp.
References AppFrameInterface::addEntite(), CPersonnage::addPersonnage(), cLua, cNiveau, cPersonnage, CLua::executeMain(), CLua::executeScript(), CPersonnage::getCurrentPerso(), MEntite::getDirection(), MEntite::getNom(), MTuile::getPosition(), CNiveau::getScript(), MObjetTexture::getTexture(), MEntite::getTuile(), CPersonnage::setPersonnage(), AppFrameInterface::setPositionOf(), thread, and vuePrincipale.
~CJeu()
CJeu::~CJeu () virtual
Definition at line 57 of file CJeu.cpp.
References vuePrincipale.
Member Function Documentation
getEntite()
MEntite * CJeu::getEntite (std::string name)
Definition at line 67 of file CJeu.cpp.
References cNiveau, and CNiveau::getEntite().
Referenced by CLua::cppAddActionDefense(), CLua::cppGiveNewItemToEntity(), and CLua::getEntite().
getPersonnage()
MPersonnage * CJeu::getPersonnage (std::string name)
Parameters
name le nom du personnage à get
Returns
le personnage du nom spécifié
Definition at line 78 of file CJeu.cpp.
References cPersonnage, and CPersonnage::getPersonnage().
Friends And Related Function Documentation
CLua
friend class CLua friend
Definition at line 26 of file CJeu.hpp.
Member Data Documentation
cLua
CLua CJeu::cLua private
Definition at line 32 of file CJeu.hpp.
Referenced by CJeu().
cNiveau
CNiveau CJeu::cNiveau private
Definition at line 30 of file CJeu.hpp.
Referenced by CJeu(), CLua::cppAddActionMining(), CLua::cppAfficherEnigme(), CLua::cppGetScriptPath(), CLua::cppLoadCouche(), CLua::cppNewEnigme(), CLua::cppNewEntity(), CLua::cppSetScriptPath(), getEntite(), CLua::getTuile(), and CLua::loadfile().
cPersonnage
CPersonnage CJeu::cPersonnage private
Definition at line 31 of file CJeu.hpp.
Referenced by CJeu(), CLua::cppGetCurrentPerso(), CLua::cppGiveNewItemToPerso(), CLua::cppNewRobot(), CLua::getEntite(), and getPersonnage().
thread
std::future<void> CJeu::thread private
Definition at line 34 of file CJeu.hpp.
Referenced by CJeu().
vuePrincipale
AppFrameInterface* CJeu::vuePrincipale private
Definition at line 29 of file CJeu.hpp.
Referenced by CJeu(), CLua::cppParler(), and ~CJeu().
The documentation for this class was generated from the following files:
src/controlleur/CJeu.hpp
src/controlleur/CJeu.cpp