A Space Story: MExceptionEntiteNonPresente Class Reference
MExceptionEntiteNonPresente Class Reference
#include <MAssException.hpp>
Public Member Functions
MExceptionEntiteNonPresente (MTuile const *tuile)
virtual ~MExceptionEntiteNonPresente ()=default
virtual std::string what () const noexcept override
Public Member Functions inherited from MAssException
MAssException (std::string desc="")
virtual ~MAssException ()=default
Private Attributes
MTuile const * tuile
Detailed Description
Exception lorsque qu'une entité n'est pas présente à un endroit (MTuile)
Definition at line 43 of file MAssException.hpp.
Constructor & Destructor Documentation
MExceptionEntiteNonPresente()
MExceptionEntiteNonPresente::MExceptionEntiteNonPresente (MTuile const * tuile)
Definition at line 40 of file MAssException.cpp.
~MExceptionEntiteNonPresente()
virtual MExceptionEntiteNonPresente::~MExceptionEntiteNonPresente () virtual default
Member Function Documentation
what()
std::string MExceptionEntiteNonPresente::what () const override virtual noexcept
Reimplemented from MAssException.
Definition at line 45 of file MAssException.cpp.
References MPartieCouche::getName(), MTuile::getPartieCouche(), MTuile::getPosition(), SOL, MCoordonnees::str(), and tuile.
Member Data Documentation
tuile
MTuile const* MExceptionEntiteNonPresente::tuile private
Definition at line 46 of file MAssException.hpp.
Referenced by what().
The documentation for this class was generated from the following files:
src/model/MAssException.hpp
src/model/MAssException.cpp