A Space Story: CLua Class Reference
CLua Class Reference
#include <CLua.hpp>
Public Member Functions
CLua (CJeu *cJeu)
virtual ~CLua ()
void executeScript (std::string script)
void executeMain ()
Private Member Functions
void registerBaseFunctions ()
void registerTerrainFunctions ()
void registerEntiteFunctions ()
void registerItemFunctions ()
void registerEnigmeFunctions ()
template<class T >
T getTableData (lua_State *l, char const *key, int paramNb=1)
Static Private Member Functions
static int cppLoadCouche (lua_State *l)
static int cppSetScriptPath (lua_State *l)
static int cppGetScriptPath (lua_State *l)
static int cppGetResourcesPath (lua_State *l)
static int loadfile (lua_State *l)
static int cppGetKeyFor (lua_State *l)
static int cppAddActionDeclenchement (lua_State *l)
static int cppAddActionPassage (lua_State *l)
static int cppAddActionMining (lua_State *l)
static int cppNewEntity (lua_State *l)
static int cppAddActionDefense (lua_State *l)
static int cppSetPosition (lua_State *l)
static int cppSetTaille (lua_State *l)
static int cppSetTexture (lua_State *l)
static int cppGetCurrentPerso (lua_State *l)
static int cppNewRobot (lua_State *l)
static int cppNewItem (lua_State *l)
static int cppGiveNewItemToPerso (lua_State *l)
static int cppGiveNewItemToEntity (lua_State *l)
static int cppPutNewItemOn (lua_State *l)
static int cppAddInventory (lua_State *l)
static int cppShowInventory (lua_State *l)
static int cppAddActionUtilisation (lua_State *l)
static int cppNewEnigme (lua_State *l)
static int cppAfficherEnigme (lua_State *l)
static int cppParler (lua_State *l)
static MTuile * getTuile (int index)
static MItem * getItem ()
static MEntite * getEntite (std::string &entiteName, int nbArgsNoEntity)
static void push (lua_Number n)
static void push (lua_Integer n)
static void push (lua_Unsigned n)
static void push (int n)
static void push (lua_String str)
static void push (lua_CFunction f)
static void push (lua_Boolean b)
static int getTop ()
static int storeFunction ()
static void pushFunctionFrom (int index)
static void testArgs (int nbExpectedMin, int nbExpectedMax)
static void testArgs (int nbExpectedMin)
static std::string getCurFunction ()
Static Private Attributes
static lua_State * lua = luaL_newstate()
static CJeu * cJeu
static MItem * item = nullptr
Detailed Description
interpreteur lua pour créer et gerer les niveaux
Definition at line 44 of file CLua.hpp.
Constructor & Destructor Documentation
CLua()
CLua::CLua (CJeu * cJeu)
Parameters
cJeu
Definition at line 45 of file CLua.cpp.
References cJeu, lua, registerBaseFunctions(), registerEnigmeFunctions(), registerEntiteFunctions(), registerItemFunctions(), and registerTerrainFunctions().
~CLua()
CLua::~CLua () virtual
Definition at line 58 of file CLua.cpp.
References lua.
Member Function Documentation
cppAddActionDeclenchement()
int CLua::cppAddActionDeclenchement (lua_State * l) static private
addActionDeclenchement(int x, int y, int couche, fonction actionDeclenchement(entite))
ajoute l'action actionDeclenchement à la couche n°couche en (x,y) déclenché lorsqu'une entité déclenche la couche(action volontaire)
Definition at line 154 of file CLua.cpp.
References MTuile::getPartieCouche(), getTuile(), push(), testArgs(), and to_string().
Referenced by registerTerrainFunctions().
cppAddActionDefense()
int CLua::cppAddActionDefense (lua_State * l) static private
addActionDefense(string entite, actionDefense(string entiteAttaquante, int degat));
Definition at line 237 of file CLua.cpp.
References cJeu, CJeu::getEntite(), push(), MEntite::setActionDefense(), and testArgs().
Referenced by registerEntiteFunctions().
cppAddActionMining()
int CLua::cppAddActionMining (lua_State * l) static private
addActionMining(string element, function(string entite, int itemId, int xMined, int yMined)) element est le nom d'un element définie dans elementList
la fonction passée en paramètre peut retourner l'id du dernier item créé (dans cette fonction par exemple) pour mettre cet item dans l'inventaire de l'entité mineuse
Definition at line 528 of file CLua.cpp.
References MEntite::addItemToInventaire(), cJeu, CJeu::cNiveau, MTerrain::getElement(), getItem(), MEntite::getNom(), CNiveau::getTerrain(), item, push(), pushFunctionFrom(), MPartieCouche::setActionMining(), storeFunction(), and testArgs().
Referenced by registerTerrainFunctions().
cppAddActionPassage()
int CLua::cppAddActionPassage (lua_State * l) static private
addActionPassage(int x, int y, int couche, fonction actionPassage(string entite))
ajoute l'action actionPassage à la couche n°couche en (x,y) déclenché lorsqu'une entité passe sur la couche(action NON volontaire)
Definition at line 191 of file CLua.cpp.
References MTuile::getPartieCouche(), getTuile(), push(), MPartieCouche::setActionPassage(), and testArgs().
Referenced by registerTerrainFunctions().
cppAddActionUtilisation()
int CLua::cppAddActionUtilisation (lua_State * l) static private
addActionUtilisation(luaFunction)
Definition at line 499 of file CLua.cpp.
References getItem(), push(), MItem::setActionUtilisation(), and testArgs().
Referenced by registerItemFunctions().
cppAddInventory()
int CLua::cppAddInventory (lua_State * l) static private
addInventory(int x, int y, int tailleX, int tailleY) permet d'ajouter un inventaire VISIBLE à la tuile de coordonnées (x, y) de taille (tailleX, tailleY)
Definition at line 474 of file CLua.cpp.
References MTuile::addInventaire(), getTuile(), and testArgs().
Referenced by registerItemFunctions().
cppAfficherEnigme()
int CLua::cppAfficherEnigme (lua_State * l) static private
afficherEnigme(nom)
Definition at line 570 of file CLua.cpp.
References CNiveau::afficherEnigme(), cJeu, CJeu::cNiveau, and testArgs().
Referenced by registerEnigmeFunctions().
cppGetCurrentPerso()
int CLua::cppGetCurrentPerso (lua_State * l) static private
string getCurrentPerso()
retourne le nom du perso courant
Definition at line 362 of file CLua.cpp.
References cJeu, CJeu::cPersonnage, CPersonnage::getCurrentPerso(), MEntite::getNom(), and testArgs().
Referenced by registerEntiteFunctions().
cppGetKeyFor()
int CLua::cppGetKeyFor (lua_State * l) static private
Definition at line 142 of file CLua.cpp.
References MParameters::getKey(), push(), and testArgs().
Referenced by registerBaseFunctions().
cppGetResourcesPath()
int CLua::cppGetResourcesPath (lua_State * l) static private
string getResourcesPath()
return le chemin vers le dossier de ressources
Definition at line 124 of file CLua.cpp.
References MParameters::getRootPath(), push(), and testArgs().
Referenced by registerBaseFunctions().
cppGetScriptPath()
int CLua::cppGetScriptPath (lua_State * l) static private
string getScriptPath()
return the current lua path and the current luaFile
Definition at line 112 of file CLua.cpp.
References cJeu, CJeu::cNiveau, CNiveau::getLevelMainFile(), CNiveau::getScriptFolder(), push(), and testArgs().
Referenced by registerBaseFunctions().
cppGiveNewItemToEntity()
int CLua::cppGiveNewItemToEntity (lua_State * l) static private
cppGiveNewItemToEntity(string nom) donne le nouvel item créé à l'entité de nom nom
Definition at line 447 of file CLua.cpp.
References MEntite::addItemToInventaire(), cJeu, CJeu::getEntite(), getItem(), item, and testArgs().
Referenced by registerItemFunctions().
cppGiveNewItemToPerso()
int CLua::cppGiveNewItemToPerso (lua_State * l) static private
cppGiveNewItemToPerso() donne le nouvel item créé au personnage courant
Definition at line 435 of file CLua.cpp.
References MEntite::addItemToInventaire(), cJeu, CJeu::cPersonnage, CPersonnage::getCurrentPerso(), getItem(), item, and testArgs().
Referenced by registerItemFunctions().
cppLoadCouche()
int CLua::cppLoadCouche (lua_State * l) static private
lua function signature :
void loadCouche(string coucheFile, int couche);
Parameters
l lua interpreter
Returns
number of returns
Definition at line 73 of file CLua.cpp.
References cJeu, CJeu::cNiveau, CNiveau::getScriptFolder(), CNiveau::getTerrain(), MTerrain::loadCouche(), and testArgs().
Referenced by registerTerrainFunctions().
cppNewEnigme()
int CLua::cppNewEnigme (lua_State * l) static private
newEnigme(nom, description, image)
Definition at line 557 of file CLua.cpp.
References CNiveau::addEnigme(), cJeu, CJeu::cNiveau, and testArgs().
Referenced by registerEnigmeFunctions().
cppNewEntity()
int CLua::cppNewEntity (lua_State * l) static private
newEntity(name, texture, x, y, taille)
Definition at line 222 of file CLua.cpp.
References CNiveau::addEntite(), cJeu, CJeu::cNiveau, getTuile(), and testArgs().
Referenced by registerEntiteFunctions().
cppNewItem()
int CLua::cppNewItem (lua_State * l) static private
newItem(nom, description, texture, degat = 0, equipement = MAIN(0), protection = 0, supprimable = true, miningLevel = 0)
Definition at line 388 of file CLua.cpp.
References MItem::getId(), getTop(), item, MAIN, push(), and testArgs().
Referenced by registerItemFunctions().
cppNewRobot()
int CLua::cppNewRobot (lua_State * l) static private
newRobot(string nom, string texture, int x, int y, float taille)
Definition at line 373 of file CLua.cpp.
References CPersonnage::addRobot(), cJeu, CJeu::cPersonnage, getTuile(), and testArgs().
Referenced by registerEntiteFunctions().
cppParler()
int CLua::cppParler (lua_State * l) static private
cppParler(string texture, string msg)
Definition at line 581 of file CLua.cpp.
References cJeu, getTop(), AppFrameInterface::parler(), testArgs(), and CJeu::vuePrincipale.
Referenced by registerEntiteFunctions().
cppPutNewItemOn()
int CLua::cppPutNewItemOn (lua_State * l) static private
cppPutNewItemOn(int x, int y) met l'item nouvellement créé sur la tuile (x, y)
Definition at line 461 of file CLua.cpp.
References MTuile::addItem(), getItem(), getTuile(), item, and testArgs().
Referenced by registerItemFunctions().
cppSetPosition()
int CLua::cppSetPosition (lua_State * l) static private
setPosition(string entiteName, int x, int y) set la position de l'entite de nom entiteName
setPosition(int x, int y)
set la position du perso
Definition at line 297 of file CLua.cpp.
References getEntite(), getTuile(), MEntite::setTuile(), and testArgs().
Referenced by registerEntiteFunctions().
cppSetScriptPath()
int CLua::cppSetScriptPath (lua_State * l) static private
setScriptPath(folder, luaFile)
set the current folder (and the luaFile to execute if 2 args are passed)
Definition at line 88 of file CLua.cpp.
References cJeu, CJeu::cNiveau, getTop(), CNiveau::setLevelMainFile(), CNiveau::setScriptFolder(), and testArgs().
Referenced by registerBaseFunctions().
cppSetTaille()
int CLua::cppSetTaille (lua_State * l) static private
setTaille(string entiteName, int taille)
set la taille de l'entité spécifiée
setTaille(int taille)
set la taille du perso courant
Definition at line 338 of file CLua.cpp.
References getEntite(), MEntite::setTaille(), and testArgs().
Referenced by registerEntiteFunctions().
cppSetTexture()
int CLua::cppSetTexture (lua_State * l) static private
setTexture(string entiteName, string texture)
set la texture de l'entité spécifiée
setTexture(string texture)
set la texture du perso courant
Definition at line 322 of file CLua.cpp.
References getEntite(), MObjetTexture::setTexture(), and testArgs().
Referenced by registerEntiteFunctions().
cppShowInventory()
int CLua::cppShowInventory (lua_State * l) static private
cppShowInventory(int x, int y) show the inventory on coords (x, y)
Definition at line 488 of file CLua.cpp.
References MTuile::getInventaire(), getTuile(), VInventaireInterface::show(), and testArgs().
Referenced by registerItemFunctions().
executeMain()
void CLua::executeMain ()
Definition at line 660 of file CLua.cpp.
References lua.
Referenced by CJeu::CJeu().
executeScript()
void CLua::executeScript (std::string script)
Definition at line 640 of file CLua.cpp.
References lua.
Referenced by CJeu::CJeu().
getCurFunction()
std::string CLua::getCurFunction () static private
Definition at line 799 of file CLua.cpp.
References lua.
Referenced by getItem(), pushFunctionFrom(), and storeFunction().
getEntite()
MEntite * CLua::getEntite (std::string & entiteName, int nbArgsNoEntity) static private
Parameters
entiteName out: le nom de l'entité retourné
nbArgsNoEntity le nombre d'argument sans compter ce qu'il faut pour prendre une entité
Returns
retourne l'entité nommée si le nom de l'entité est spécifié (getTop() - nbArgsNoEntity == 1) sinon retourne le personnage courant
Definition at line 271 of file CLua.cpp.
References cJeu, CJeu::cPersonnage, CPersonnage::getCurrentPerso(), CJeu::getEntite(), MEntite::getNom(), getTop(), and lua.
Referenced by cppSetPosition(), cppSetTaille(), and cppSetTexture().
getItem()
MItem * CLua::getItem () static private
Definition at line 690 of file CLua.cpp.
References getCurFunction(), item, and MAssException::what().
Referenced by cppAddActionMining(), cppAddActionUtilisation(), cppGiveNewItemToEntity(), cppGiveNewItemToPerso(), and cppPutNewItemOn().
getTableData()
template<class T > T CLua::getTableData (lua_State * l, char const * key, int paramNb = 1) private
Parameters
l l'interpreteur lua
key la clé que l'on veut récupérer (like : map["key"])
paramNb là où se trouve la table (map) dans la pile lua
Returns
Definition at line 163 of file CLua.hpp.
getTop()
int CLua::getTop () static private
Definition at line 742 of file CLua.cpp.
References lua.
Referenced by cppNewItem(), cppParler(), cppSetScriptPath(), and getEntite().
getTuile()
MTuile * CLua::getTuile (int index) static private
Parameters
index a partir du quel sont rangé le x, y dans la pile lua
Returns
la tuile en (x, y) pris depuis l'index
Definition at line 683 of file CLua.cpp.
References cJeu, CJeu::cNiveau, CNiveau::getTerrain(), and lua.
Referenced by cppAddActionDeclenchement(), cppAddActionPassage(), cppAddInventory(), cppNewEntity(), cppNewRobot(), cppPutNewItemOn(), cppSetPosition(), and cppShowInventory().
loadfile()
int CLua::loadfile (lua_State * l) static private
redefinie le comportement du loadfile pour prendre en compte le chemin vers le dossier du script "courant"
Definition at line 134 of file CLua.cpp.
References cJeu, CJeu::cNiveau, CNiveau::getScriptFolder(), and testArgs().
Referenced by registerBaseFunctions().
push() [1/7]
void CLua::push (lua_Number n) static private
Definition at line 722 of file CLua.cpp.
References lua.
Referenced by cppAddActionDeclenchement(), cppAddActionDefense(), cppAddActionMining(), cppAddActionPassage(), cppAddActionUtilisation(), cppGetKeyFor(), cppGetResourcesPath(), cppGetScriptPath(), and cppNewItem().
push() [2/7]
void CLua::push (lua_Integer n) static private
Definition at line 727 of file CLua.cpp.
References lua.
push() [3/7]
void CLua::push (lua_Unsigned n) static private
Definition at line 732 of file CLua.cpp.
References lua.
push() [4/7]
void CLua::push (int n) static private
Definition at line 737 of file CLua.cpp.
References lua.
push() [5/7]
void CLua::push (lua_String str) static private
Definition at line 717 of file CLua.cpp.
References lua.
push() [6/7]
void CLua::push (lua_CFunction f) static private
Definition at line 712 of file CLua.cpp.
References lua.
push() [7/7]
void CLua::push (lua_Boolean b) static private
Definition at line 707 of file CLua.cpp.
References lua.
pushFunctionFrom()
void CLua::pushFunctionFrom (int index) static private
Definition at line 758 of file CLua.cpp.
References getCurFunction(), and lua.
Referenced by cppAddActionMining().
registerBaseFunctions()
void CLua::registerBaseFunctions () private
Definition at line 590 of file CLua.cpp.
References cppGetKeyFor(), cppGetResourcesPath(), cppGetScriptPath(), cppSetScriptPath(), loadfile(), and lua.
Referenced by CLua().
registerEnigmeFunctions()
void CLua::registerEnigmeFunctions () private
Definition at line 634 of file CLua.cpp.
References cppAfficherEnigme(), cppNewEnigme(), and lua.
Referenced by CLua().
registerEntiteFunctions()
void CLua::registerEntiteFunctions () private
Definition at line 608 of file CLua.cpp.
References cppAddActionDefense(), cppGetCurrentPerso(), cppNewEntity(), cppNewRobot(), cppParler(), cppSetPosition(), cppSetTaille(), cppSetTexture(), and lua.
Referenced by CLua().
registerItemFunctions()
void CLua::registerItemFunctions () private
Definition at line 622 of file CLua.cpp.
References cppAddActionUtilisation(), cppAddInventory(), cppGiveNewItemToEntity(), cppGiveNewItemToPerso(), cppNewItem(), cppPutNewItemOn(), cppShowInventory(), and lua.
Referenced by CLua().
registerTerrainFunctions()
void CLua::registerTerrainFunctions () private
Definition at line 599 of file CLua.cpp.
References cppAddActionDeclenchement(), cppAddActionMining(), cppAddActionPassage(), cppLoadCouche(), and lua.
Referenced by CLua().
storeFunction()
int CLua::storeFunction () static private
Definition at line 747 of file CLua.cpp.
References getCurFunction(), and lua.
Referenced by cppAddActionMining().
testArgs() [1/2]
void CLua::testArgs (int nbExpectedMin, int nbExpectedMax) static private
Definition at line 769 of file CLua.cpp.
References lua, to_string(), and MAssException::what().
Referenced by cppAddActionDeclenchement(), cppAddActionDefense(), cppAddActionMining(), cppAddActionPassage(), cppAddActionUtilisation(), cppAddInventory(), cppAfficherEnigme(), cppGetCurrentPerso(), cppGetKeyFor(), cppGetResourcesPath(), cppGetScriptPath(), cppGiveNewItemToEntity(), cppGiveNewItemToPerso(), cppLoadCouche(), cppNewEnigme(), cppNewEntity(), cppNewItem(), cppNewRobot(), cppParler(), cppPutNewItemOn(), cppSetPosition(), cppSetScriptPath(), cppSetTaille(), cppSetTexture(), cppShowInventory(), loadfile(), and testArgs().
testArgs() [2/2]
void CLua::testArgs (int nbExpectedMin) static private
Definition at line 794 of file CLua.cpp.
References testArgs().
Member Data Documentation
cJeu
CJeu * CLua::cJeu static private
pointeur vers la "racine" du jeu
utilisé pour les fonctions appelées depuis le lua (eg: pour faire les niveaux)
Definition at line 60 of file CLua.hpp.
Referenced by CLua(), cppAddActionDefense(), cppAddActionMining(), cppAfficherEnigme(), cppGetCurrentPerso(), cppGetScriptPath(), cppGiveNewItemToEntity(), cppGiveNewItemToPerso(), cppLoadCouche(), cppNewEnigme(), cppNewEntity(), cppNewRobot(), cppParler(), cppSetScriptPath(), getEntite(), getTuile(), and loadfile().
item
MItem * CLua::item = nullptr static private
Definition at line 61 of file CLua.hpp.
Referenced by cppAddActionMining(), cppGiveNewItemToEntity(), cppGiveNewItemToPerso(), cppNewItem(), cppPutNewItemOn(), and getItem().
lua
lua_State * CLua::lua = luaL_newstate() static private
l'interpreteur lua
See also
le manuel lua
la pile lua
detail de la pile
Definition at line 55 of file CLua.hpp.
Referenced by CLua(), executeMain(), executeScript(), getCurFunction(), getEntite(), getTop(), getTuile(), push(), pushFunctionFrom(), registerBaseFunctions(), registerEnigmeFunctions(), registerEntiteFunctions(), registerItemFunctions(), registerTerrainFunctions(), storeFunction(), testArgs(), and ~CLua().
The documentation for this class was generated from the following files:
src/controlleur/CLua.hpp
src/controlleur/CLua.cpp