A Space Story: CPersonnage Class Reference
CPersonnage Class Reference
#include <CPersonnage.hpp>
Public Member Functions
CPersonnage (AppFrameInterface *vuePrincipale, MTerrain *terrain)
virtual ~CPersonnage ()
bool setPersonnage (std::string nom)
MPersonnage * getPersonnage (std::string nom)
MPersonnage * getCurrentPerso ()
void addPersonnage (std::string nom)
void addRobot (std::string const &nom, std::string const &texture, MTuile *tuile, float taille)
Private Member Functions
void setEventMethods ()
Private Attributes
AppFrameInterface * vuePrincipale
CEditor editor
std::map< std::string, MPersonnage > personnages
MPersonnage * currentPerso
MTerrain * terrain
bool quit
Detailed Description
le controlleur pour gérer les déplacements, les interactions du personnage (comme il est indépendant des niveaux)
Definition at line 28 of file CPersonnage.hpp.
Constructor & Destructor Documentation
CPersonnage()
CPersonnage::CPersonnage (AppFrameInterface * vuePrincipale, MTerrain * terrain)
Definition at line 34 of file CPersonnage.cpp.
References setEventMethods().
~CPersonnage()
CPersonnage::~CPersonnage () virtual
Definition at line 40 of file CPersonnage.cpp.
Member Function Documentation
addPersonnage()
void CPersonnage::addPersonnage (std::string nom) inline
Definition at line 97 of file CPersonnage.hpp.
References personnages.
Referenced by CJeu::CJeu().
addRobot()
void CPersonnage::addRobot (std::string const & nom, std::string const & texture, MTuile * tuile, float taille)
Definition at line 109 of file CPersonnage.cpp.
References AppFrameInterface::addEntite(), currentPerso, editor, MEntite::getDirection(), MEntite::getNom(), MTuile::getPosition(), MPersonnage::getRobot(), MPersonnage::makeRobot(), MEntite::setActionInteraction(), AppFrameInterface::setPositionOf(), and vuePrincipale.
Referenced by CLua::cppNewRobot().
getCurrentPerso()
MPersonnage * CPersonnage::getCurrentPerso () inline
Definition at line 92 of file CPersonnage.hpp.
References currentPerso.
Referenced by CJeu::CJeu(), CLua::cppGetCurrentPerso(), CLua::cppGiveNewItemToPerso(), and CLua::getEntite().
getPersonnage()
MPersonnage * CPersonnage::getPersonnage (std::string nom) inline
Definition at line 82 of file CPersonnage.hpp.
References personnages.
Referenced by CJeu::getPersonnage().
setEventMethods()
void CPersonnage::setEventMethods () private
Definition at line 46 of file CPersonnage.cpp.
References MEntite::attaquer(), currentPerso, MEntite::deplacer(), editor, ELEMENT, ENTITY_MOVED, EXIT, MParameters::getActionFromKey(), MTerrain::getImagesList(), MParameters::getMouvFromKey(), MParameters::getTailleTuile(), MParameters::getTextureFor(), INTERACT_ENTITY_KEY, INTERACT_ENV, MEntite::interagirEntite(), MEntite::interagirTuile(), MParameters::isActionKey(), MParameters::isMouvKey(), KEY_PRESSED, AppFrameInterface::loadFileIntoGround(), MINE, MEntite::mine(), OPEN_EDITOR, OPEN_INVENTORY, quit, AppFrameInterface::setPositionOf(), terrain, USE_MAIN_OBJECT, MEntite::utiliserObjet(), and vuePrincipale.
Referenced by CPersonnage().
setPersonnage()
bool CPersonnage::setPersonnage (std::string nom) inline
Definition at line 71 of file CPersonnage.hpp.
References currentPerso, and personnages.
Referenced by CJeu::CJeu().
Member Data Documentation
currentPerso
MPersonnage* CPersonnage::currentPerso private
Definition at line 36 of file CPersonnage.hpp.
Referenced by addRobot(), getCurrentPerso(), setEventMethods(), and setPersonnage().
editor
CEditor CPersonnage::editor private
Definition at line 33 of file CPersonnage.hpp.
Referenced by addRobot(), and setEventMethods().
personnages
std::map<std::string, MPersonnage> CPersonnage::personnages private
Definition at line 35 of file CPersonnage.hpp.
Referenced by addPersonnage(), getPersonnage(), and setPersonnage().
quit
bool CPersonnage::quit private
Deprecated:
ne sert plus, version non graphique
Definition at line 41 of file CPersonnage.hpp.
Referenced by setEventMethods().
terrain
MTerrain* CPersonnage::terrain private
Definition at line 37 of file CPersonnage.hpp.
Referenced by setEventMethods().
vuePrincipale
AppFrameInterface* CPersonnage::vuePrincipale private
Definition at line 32 of file CPersonnage.hpp.
Referenced by addRobot(), and setEventMethods().
The documentation for this class was generated from the following files:
src/controlleur/CPersonnage.hpp
src/controlleur/CPersonnage.cpp