A Space Story: MParameters Class Reference
MParameters Class Reference
#include <MParameters.hpp>
Static Public Member Functions
static std::string getRootPath ()
static std::string getConfPath ()
static std::string getTuilePath ()
static std::string getLevelPath ()
static std::string getMainScriptFolder ()
static std::string getMainScript ()
static std::string getSolsPath ()
static std::string getElementsPath ()
static std::string getCielsPath ()
static Mouvement getMouvFromKey (char key)
static MActionsKey getActionFromKey (char key)
static bool isMouvKey (char key)
static bool isActionKey (char key)
static std::string getTextureFor (MTypeCouche couche)
static int getTailleTuile ()
static int getNbTuileX ()
static int getNbTuileY ()
static std::string getSpritesPath ()
static void load (std::string exePath)
Static Private Member Functions
static bool checkConfFile (std::string path)
static void setRootPath ()
static char getKeyFor (std::string const &action)
Static Private Attributes
static std::map< std::string, std::string > conf
static auto constexpr configFile = "SbiAss.conf"
static std::string rootPath
static std::map< char, Mouvement > mouvKeys
static std::map< char, MActionsKey > keys
Detailed Description
List of parameters for editor
Definition at line 37 of file MParameters.hpp.
Member Function Documentation
checkConfFile()
bool MParameters::checkConfFile (std::string path) static private
set and check the configroot path
Parameters
path new path
Returns
true if we can open this new configRoot path
Definition at line 18 of file MParameters.cpp.
References getConfPath(), and rootPath.
Referenced by setRootPath().
getActionFromKey()
MActionsKey MParameters::getActionFromKey (char key) static
Definition at line 109 of file MParameters.cpp.
References keys.
Referenced by CPersonnage::setEventMethods().
getCielsPath()
std::string MParameters::getCielsPath () static
Definition at line 79 of file MParameters.cpp.
References conf, and getTuilePath().
Referenced by MTerrain::loadTypes().
getConfPath()
std::string MParameters::getConfPath () static
Definition at line 64 of file MParameters.cpp.
References configFile, and rootPath.
Referenced by checkConfFile(), and load().
getElementsPath()
std::string MParameters::getElementsPath () static
Definition at line 74 of file MParameters.cpp.
References conf, and getTuilePath().
Referenced by MTerrain::loadTypes().
getKeyFor()
char MParameters::getKeyFor (std::string const & action) static private
Definition at line 46 of file MParameters.cpp.
References conf.
Referenced by load().
getLevelPath()
std::string MParameters::getLevelPath () static
Definition at line 89 of file MParameters.cpp.
References conf, and rootPath.
Referenced by CNiveau::getScript(), and CNiveau::getScriptFolder().
getMainScript()
std::string MParameters::getMainScript () static
Definition at line 99 of file MParameters.cpp.
References conf.
getMainScriptFolder()
std::string MParameters::getMainScriptFolder () static
Definition at line 94 of file MParameters.cpp.
References conf.
getMouvFromKey()
Mouvement MParameters::getMouvFromKey (char key) static
Definition at line 104 of file MParameters.cpp.
References mouvKeys.
Referenced by CPersonnage::setEventMethods().
getNbTuileX()
int MParameters::getNbTuileX () static
Definition at line 146 of file MParameters.cpp.
References conf.
Referenced by MTerrain::MTerrain().
getNbTuileY()
int MParameters::getNbTuileY () static
Definition at line 151 of file MParameters.cpp.
References conf.
Referenced by MTerrain::MTerrain().
getRootPath()
std::string MParameters::getRootPath () static
Definition at line 59 of file MParameters.cpp.
References rootPath.
Referenced by CLua::getResourcesPath(), and getSpritesPath().
getSolsPath()
std::string MParameters::getSolsPath () static
Definition at line 69 of file MParameters.cpp.
References conf, and getTuilePath().
Referenced by MTerrain::loadTypes().
getSpritesPath()
std::string MParameters::getSpritesPath () static
Definition at line 156 of file MParameters.cpp.
References conf, and getRootPath().
getTailleTuile()
int MParameters::getTailleTuile () static
Definition at line 141 of file MParameters.cpp.
References conf.
Referenced by CNiveau::setEventMethods().
getTextureFor()
std::string MParameters::getTextureFor (MTypeCouche couche) static
Definition at line 136 of file MParameters.cpp.
References conf, getTuilePath(), and to_string().
Referenced by CNiveau::setEventMethods().
getTuilePath()
std::string MParameters::getTuilePath () static
Definition at line 84 of file MParameters.cpp.
References conf, and rootPath.
Referenced by getCielsPath(), getElementsPath(), getSolsPath(), and getTextureFor().
isActionKey()
bool MParameters::isActionKey (char key) static
Definition at line 125 of file MParameters.cpp.
References keys.
Referenced by CPersonnage::setEventMethods().
isMouvKey()
bool MParameters::isMouvKey (char key) static
Definition at line 114 of file MParameters.cpp.
References mouvKeys.
Referenced by CPersonnage::setEventMethods().
load()
void MParameters::load (std::string exePath) static
Definition at line 161 of file MParameters.cpp.
References ATTACK, BAS, conf, DROITE, GAUCHE, getConfPath(), getKeyFor(), HAUT, INTERACT_ENTITY_KEY, INTERACT_ENV_KEY, keys, mouvKeys, rootPath, and setRootPath().
Referenced by main(), and App::OnInit().
setRootPath()
void MParameters::setRootPath () static private
init the rootPath with the rootPath itself, it seeking for the rootFile in another known folders
Definition at line 34 of file MParameters.cpp.
References checkConfFile(), and rootPath.
Referenced by load().
Member Data Documentation
conf
std::map< std::string, std::string > MParameters::conf static private
Definition at line 42 of file MParameters.hpp.
Referenced by getCielsPath(), getElementsPath(), getKeyFor(), getLevelPath(), getMainScript(), getMainScriptFolder(), getNbTuileX(), getNbTuileY(), getSolsPath(), getSpritesPath(), getTailleTuile(), getTextureFor(), getTuilePath(), and load().
configFile
auto constexpr MParameters::configFile = "SbiAss.conf" static private
Definition at line 43 of file MParameters.hpp.
Referenced by getConfPath().
keys
std::map< char, MActionsKey > MParameters::keys static private
Definition at line 47 of file MParameters.hpp.
Referenced by getActionFromKey(), isActionKey(), and load().
mouvKeys
std::map< char, Mouvement > MParameters::mouvKeys static private
Definition at line 46 of file MParameters.hpp.
Referenced by getMouvFromKey(), isMouvKey(), and load().
rootPath
std::string MParameters::rootPath static private
Definition at line 44 of file MParameters.hpp.
Referenced by checkConfFile(), getConfPath(), getLevelPath(), getRootPath(), getTuilePath(), load(), and setRootPath().
The documentation for this class was generated from the following files:
src/model/MParameters.hpp
src/model/MParameters.cpp