A Space Story: MPartieCoucheElement Class Reference
MPartieCoucheElement Class Reference
#include <MPartieCoucheElement.hpp>
Public Member Functions
MPartieCoucheElement (Id ID, MTypeCouche type, std::string name, std::string fichierImg, float placeDispo, int miningLevel=-1)
MPartieCoucheElement (MPartieCoucheElement const &)
MPartieCoucheElement & operator= (MPartieCoucheElement const &)
virtual ~MPartieCoucheElement ()
void mine (MEntite *entite, int item, MCoordonnees minedCoords) override
int getMiningLevel () const override
void setActionMining (std::function< void(MEntite *entite, int item, int xMined, int yMined)> actionMining) override
void unSetActionMining () override
Public Member Functions inherited from MPartieCouche
MPartieCouche (int id, MTypeCouche type, std::string name, std::string fichierImg, float placeDispo)
MPartieCouche (MPartieCouche const &other)
virtual MPartieCouche & operator= (MPartieCouche const &other)
virtual ~MPartieCouche ()
bool isTypeOf (MTypeCouche type) const
void passageDe (MEntite *entite)
void declenchementDe (MEntite *entite)
bool isNull () const
int getId () const
void setId (int id)
MTypeCouche const & getType () const
std::string const & getName () const
std::string const & getFichierImg () const
float getPlaceDispo () const
void setFichierImg (std::string const &fichierImg)
void setActionDeclenchement (std::function< void(std::string entite)> actionDeclenchement)
void setActionPassage (std::function< void(std::string entite)> actionPassage)
void unSetActionDeclenchement ()
void unSetActionPassage ()
Private Attributes
int miningLevel
std::shared_ptr< std::function< void(MEntite *entite, int item, int xMined, int yMined)> > actionMining
Additional Inherited Members
Static Public Attributes inherited from MPartieCouche
static float constexpr PLACE_MAX = 1
Detailed Description
Definition at line 21 of file MPartieCoucheElement.hpp.
Constructor & Destructor Documentation
MPartieCoucheElement() [1/2]
MPartieCoucheElement::MPartieCoucheElement (Id ID, MTypeCouche type, std::string name, std::string fichierImg, float placeDispo, int miningLevel = -1)
Definition at line 28 of file MPartieCoucheElement.cpp.
MPartieCoucheElement() [2/2]
MPartieCoucheElement::MPartieCoucheElement (MPartieCoucheElement const & other)
Definition at line 38 of file MPartieCoucheElement.cpp.
~MPartieCoucheElement()
MPartieCoucheElement::~MPartieCoucheElement () virtual
Definition at line 51 of file MPartieCoucheElement.cpp.
Member Function Documentation
getMiningLevel()
int MPartieCoucheElement::getMiningLevel () const override virtual
Reimplemented from MPartieCouche.
Definition at line 93 of file MPartieCoucheElement.cpp.
References miningLevel.
mine()
void MPartieCoucheElement::mine (MEntite * entite, int item, MCoordonnees minedCoords) override virtual
Reimplemented from MPartieCouche.
Definition at line 58 of file MPartieCoucheElement.cpp.
References actionMining, MPartieCouche::getFichierImg(), MPartieCouche::getId(), MPartieCouche::getType(), MTerrain::getTypeList(), MCoordonnees::getX(), MCoordonnees::getY(), MThreads::parallelize(), MPartieCouche::setFichierImg(), and MPartieCouche::setId().
operator=()
MPartieCoucheElement & MPartieCoucheElement::operator= (MPartieCoucheElement const & other)
Definition at line 43 of file MPartieCoucheElement.cpp.
References actionMining, miningLevel, and MPartieCouche::operator=().
setActionMining()
void MPartieCoucheElement::setActionMining (std::function< void(MEntite *entite, int item, int xMined, int yMined)> actionMining) override virtual
Reimplemented from MPartieCouche.
Definition at line 82 of file MPartieCoucheElement.cpp.
References actionMining.
unSetActionMining()
void MPartieCoucheElement::unSetActionMining () override virtual
Reimplemented from MPartieCouche.
Definition at line 88 of file MPartieCoucheElement.cpp.
References actionMining.
Member Data Documentation
actionMining
std::shared_ptr<std::function<void(MEntite* entite, int item, int xMined, int yMined)> > MPartieCoucheElement::actionMining private
action when this couche is mined THIS POINTER is copied !! it's to share the action between all same couche
Definition at line 30 of file MPartieCoucheElement.hpp.
Referenced by mine(), operator=(), setActionMining(), and unSetActionMining().
miningLevel
int MPartieCoucheElement::miningLevel private
Definition at line 25 of file MPartieCoucheElement.hpp.
Referenced by getMiningLevel(), and operator=().
The documentation for this class was generated from the following files:
src/model/MPartieCoucheElement.hpp
src/model/MPartieCoucheElement.cpp