A Space Story: MInventaire Class Reference
MInventaire Class Reference
#include <MInventaire.hpp>
Public Member Functions
MInventaire (int taille)
void ajouterItem (MItem *item)
void supprimerItem (Id idItem)
bool estEquipe (MTypeEquipement typeEquip) const
void equipe (Id itemId)
void desequipe (MTypeEquipement typeEquip)
MItem * getEquipement (MTypeEquipement typeEquipement)
MItem * getItem (Id itemId)
int getForceEquipement () const
int getDefenseEquipement () const
int getDegatEquipement (MTypeEquipement typeEquip) const
int getDefenseEquipement (MTypeEquipement typeEquip) const
Private Attributes
std::array< MItem *, 5 > equipement
std::vector< MItem * > items
unsigned int taille
Detailed Description
Definition at line 32 of file MInventaire.hpp.
Constructor & Destructor Documentation
MInventaire()
MInventaire::MInventaire (int taille)
Definition at line 15 of file MInventaire.cpp.
References taille.
Member Function Documentation
ajouterItem()
void MInventaire::ajouterItem (MItem * item)
Definition at line 93 of file MInventaire.cpp.
References items, and taille.
Referenced by MEntite::addItemToInventaire(), and desequipe().
desequipe()
void MInventaire::desequipe (MTypeEquipement typeEquip)
Definition at line 84 of file MInventaire.cpp.
References ajouterItem(), equipement, estEquipe(), and getEquipement().
Referenced by equipe().
equipe()
void MInventaire::equipe (Id itemId)
Definition at line 29 of file MInventaire.cpp.
References desequipe(), equipement, getItem(), MItem::getType(), and supprimerItem().
Referenced by MEntite::equipe().
estEquipe()
bool MInventaire::estEquipe (MTypeEquipement typeEquip) const
Definition at line 79 of file MInventaire.cpp.
References equipement, and SIZE.
Referenced by desequipe(), getDefenseEquipement(), getDegatEquipement(), getForceEquipement(), and MEntite::getMiningPower().
getDefenseEquipement() [1/2]
int MInventaire::getDefenseEquipement () const
Definition at line 66 of file MInventaire.cpp.
References estEquipe(), MAIN, and SIZE.
Referenced by MEntite::defenseTotale().
getDefenseEquipement() [2/2]
int MInventaire::getDefenseEquipement (MTypeEquipement typeEquip) const
Definition at line 44 of file MInventaire.cpp.
References equipement, and estEquipe().
getDegatEquipement()
int MInventaire::getDegatEquipement (MTypeEquipement typeEquip) const
Definition at line 20 of file MInventaire.cpp.
References equipement, and estEquipe().
Referenced by getForceEquipement().
getEquipement()
MItem * MInventaire::getEquipement (MTypeEquipement typeEquipement)
Definition at line 110 of file MInventaire.cpp.
References equipement.
Referenced by desequipe(), MEntite::getMiningPower(), and MEntite::utiliserObjet().
getForceEquipement()
int MInventaire::getForceEquipement () const
Definition at line 53 of file MInventaire.cpp.
References estEquipe(), getDegatEquipement(), MAIN, and SIZE.
Referenced by MEntite::forceTotale().
getItem()
MItem * MInventaire::getItem (Id itemId)
Definition at line 115 of file MInventaire.cpp.
References equipement.
Referenced by equipe().
supprimerItem()
void MInventaire::supprimerItem (Id idItem)
Definition at line 101 of file MInventaire.cpp.
References items.
Referenced by equipe().
Member Data Documentation
equipement
std::array<MItem*, 5> MInventaire::equipement private
Definition at line 37 of file MInventaire.hpp.
Referenced by desequipe(), equipe(), estEquipe(), getDefenseEquipement(), getDegatEquipement(), getEquipement(), and getItem().
items
std::vector<MItem*> MInventaire::items private
Definition at line 38 of file MInventaire.hpp.
Referenced by ajouterItem(), and supprimerItem().
taille
unsigned int MInventaire::taille private
Definition at line 39 of file MInventaire.hpp.
Referenced by ajouterItem(), and MInventaire().
The documentation for this class was generated from the following files:
src/model/MInventaire.hpp
src/model/MInventaire.cpp