A Space Story: MTuile Class Reference
MTuile Class Reference
#include <MTuile.hpp>
Public Member Functions
MTuile (MCoordonnees const &position, MPartieCouche const &couche)
MTuile (MTuile const &)=delete
MTuile const & operator= (MTuile const &)=delete
virtual ~MTuile ()
operator MCoordonnees () const
float getPlaceDispo () const
bool isAdjacente (MTuile const &tuileOther) const
bool deplacerEntiteVers (MTuile &tuileDst)
void interagirTuile (MEntite *entite)
void mine (MEntite *entite, int item)
void addItem (MItem *item)
void addInventaire (MCoordonnees taille)
MCoordonnees const & getPosition () const
void deletePartieCouche (MTypeCouche typeCouche)
MEntite * getEntite ()
MEntite const * getEntite () const
bool isEntitePresente () const
void placeEntite (MEntite *entite)
MPartieCouche * getPartieCouche (MTypeCouche type)
bool hasPartieCouche (MTypeCouche type) const
MPartieCouche const * getPartieCouche (MTypeCouche type) const
void setPartieCouche (MPartieCouche const &couche)
VInventaireInterface * getInventaire ()
Private Member Functions
float getPlaceDispoOn (MTypeCouche const &typeCouche) const
Private Attributes
std::array< MPartieCouche *, 3 > couches
std::vector< MItem * > items
VInventaireInterface * vItems
MCoordonnees position
MEntite * entite
Detailed Description
Représente une partie du MTerrain,\ et permet de stocker une entité, des objets, et des couches(sol, elements, ciel)
Definition at line 30 of file MTuile.hpp.
Constructor & Destructor Documentation
MTuile() [1/2]
MTuile::MTuile (MCoordonnees const & position, MPartieCouche const & couche)
MTuile.cpp
Early optimization is the root of all evil
Created on: 10 nov. 2017 Author: nihil
Parameters
position la position de la tuile sur le MTerrain
id l'id de la couche sol (définie dans la solList)
nameCoucheSol le nom de la couche sol de la tuile
fichierImg le nom du fichier image de la COUCHE SOL
placeDispoSol sa place disponible
Definition at line 36 of file MTuile.cpp.
References entite, position, setPartieCouche(), and SOL.
MTuile() [2/2]
MTuile::MTuile (MTuile const &) delete
constructeur de recopie supprimé\ on ne veut pas pouvoir copier la tuile
~MTuile()
MTuile::~MTuile () virtual
Definition at line 49 of file MTuile.cpp.
References couches.
Member Function Documentation
addInventaire()
void MTuile::addInventaire (MCoordonnees taille)
Definition at line 157 of file MTuile.cpp.
References ELEMENT, MPartieCouche::getName(), getPartieCouche(), getPosition(), hasPartieCouche(), SOL, and vItems.
Referenced by CLua::cppAddInventory().
addItem()
void MTuile::addItem (MItem * item)
Definition at line 147 of file MTuile.cpp.
References VInventaireInterface::addObjInv(), MItem::getDescription(), MItem::getId(), MItem::getNom(), MObjetTexture::getTexture(), items, and vItems.
Referenced by CLua::cppPutNewItemOn().
deletePartieCouche()
void MTuile::deletePartieCouche (MTypeCouche typeCouche)
Definition at line 186 of file MTuile.cpp.
References couches, ELEMENT, and MTerrain::getTypeList().
deplacerEntiteVers()
bool MTuile::deplacerEntiteVers (MTuile & tuileDst)
déplace l'entite de la tuile this vers la tuile tuileDst
Parameters
tuileDst la tuile de destination de l'entité
Return values
true si l'entité à été déplacée
Definition at line 108 of file MTuile.cpp.
References entite, getPlaceDispo(), MEntite::getTaille(), isEntitePresente(), and placeEntite().
Referenced by MEntite::deplacer(), and MEntite::setTuile().
getEntite() [1/2]
MEntite * MTuile::getEntite () inline
Definition at line 114 of file MTuile.hpp.
References entite.
getEntite() [2/2]
MEntite const * MTuile::getEntite () const
Definition at line 217 of file MTuile.cpp.
References entite.
getInventaire()
VInventaireInterface * MTuile::getInventaire ()
Definition at line 261 of file MTuile.cpp.
References vItems.
Referenced by CLua::cppShowInventory().
getPartieCouche() [1/2]
MPartieCouche * MTuile::getPartieCouche (MTypeCouche type) inline
Parameters
type le type de la couche voulu
Returns
la couche du type spécifié (modifiable)
Definition at line 133 of file MTuile.hpp.
References couches.
Referenced by addInventaire(), CLua::cppAddActionDeclenchement(), CLua::cppAddActionPassage(), hasPartieCouche(), interagirTuile(), mine(), placeEntite(), and MExceptionEntiteNonPresente::what().
getPartieCouche() [2/2]
MPartieCouche const * MTuile::getPartieCouche (MTypeCouche type) const inline
Parameters
type le type de la couche voulu
Returns
la couche du type spécifié (NON modifiable)
Definition at line 145 of file MTuile.hpp.
References couches.
getPlaceDispo()
float MTuile::getPlaceDispo () const
Returns
la place total disponible sur la TUILE\ en fonction des différentes MPartieCouche
Definition at line 65 of file MTuile.cpp.
References CIEL, ELEMENT, entite, getPlaceDispoOn(), and SOL.
Referenced by deplacerEntiteVers().
getPlaceDispoOn()
float MTuile::getPlaceDispoOn (MTypeCouche const & typeCouche) const private
Definition at line 174 of file MTuile.cpp.
References couches, and MPartieCouche::PLACE_MAX.
Referenced by getPlaceDispo().
getPosition()
MCoordonnees const & MTuile::getPosition () const inline
Definition at line 109 of file MTuile.hpp.
References position.
Referenced by CNiveau::addEntite(), addInventaire(), CPersonnage::addRobot(), CJeu::CJeu(), MEntite::deplacer(), MTerrain::getAdjacentes(), MEntite::interagirTuile(), isAdjacente(), MRobot::isReset(), mine(), MEntite::mine(), operator MCoordonnees(), and MExceptionEntiteNonPresente::what().
hasPartieCouche()
bool MTuile::hasPartieCouche (MTypeCouche type) const
Definition at line 222 of file MTuile.cpp.
References getPartieCouche(), and MPartieCouche::isNull().
Referenced by addInventaire().
interagirTuile()
void MTuile::interagirTuile (MEntite * entite)
permet de déclancher les effet de la tuile
Parameters
entite entité interagissant
Definition at line 129 of file MTuile.cpp.
References MPartieCouche::declenchementDe(), getPartieCouche(), VInventaireInterface::show(), SIZE, and vItems.
Referenced by MEntite::interagirTuile().
isAdjacente()
bool MTuile::isAdjacente (MTuile const & tuileOther) const
Parameters
tuileOther la tuile à comparer avec this
Return values
true si tuileOther est à coté de la tuile this (diagonales non comprises)
Definition at line 89 of file MTuile.cpp.
References getPosition(), and MouvementT::size().
Referenced by MEntite::isAccessible().
isEntitePresente()
bool MTuile::isEntitePresente () const inline
Return values
true si une entité est sur la tuile
Definition at line 123 of file MTuile.hpp.
References entite.
Referenced by deplacerEntiteVers().
mine()
void MTuile::mine (MEntite * entite, int item)
active l'action de minage de la couche puis la "supprime"
Parameters
entite entité qui mine
item item qui mine
Definition at line 208 of file MTuile.cpp.
References ELEMENT, MPartieCouche::getMiningLevel(), getPartieCouche(), getPosition(), and MPartieCouche::mine().
Referenced by MEntite::mine().
operator MCoordonnees()
MTuile::operator MCoordonnees () const inline
Opérateur de cast permet de caster la tuile en position:\ (MCoordonnees)tuile
Returns
la position de la tuile
Definition at line 104 of file MTuile.hpp.
References getPosition().
operator=()
MTuile const& MTuile::operator= (MTuile const &) delete
placeEntite()
void MTuile::placeEntite (MEntite * entite) inline
Definition at line 150 of file MTuile.hpp.
References entite, MEntite::getNom(), getPartieCouche(), MPartieCouche::passageDe(), and SIZE.
Referenced by deplacerEntiteVers(), and MEntite::setTuile().
setPartieCouche()
void MTuile::setPartieCouche (MPartieCouche const & couche)
Parameters
id l'id définie dans la *List (eg: solList), permet de récupérer une image en fonction d'une couleur indéxée (gimp ^^)
type le type de la couche (sol, element, ciel)
name le nom (eg: montagne, herbe)
fichierImg doit être carré
placeDispo de 0 à 1 définie la place qu'il y a sur cette couche
Definition at line 234 of file MTuile.cpp.
References couches, ELEMENT, MPartieCouche::getType(), and MPartieCouche::isTypeOf().
Referenced by MTuile().
Member Data Documentation
couches
std::array<MPartieCouche*, 3> MTuile::couches private
pour representer le sol, l'endroit ou l'on se déplace (elements) et le ciel\
Definition at line 39 of file MTuile.hpp.
Referenced by deletePartieCouche(), getPartieCouche(), getPlaceDispoOn(), setPartieCouche(), and ~MTuile().
entite
MEntite* MTuile::entite private
Definition at line 44 of file MTuile.hpp.
Referenced by deplacerEntiteVers(), getEntite(), getPlaceDispo(), isEntitePresente(), MTuile(), and placeEntite().
items
std::vector<MItem*> MTuile::items private
Definition at line 40 of file MTuile.hpp.
Referenced by addItem().
position
MCoordonnees MTuile::position private
Definition at line 42 of file MTuile.hpp.
Referenced by getPosition(), and MTuile().
vItems
VInventaireInterface* MTuile::vItems private
Definition at line 41 of file MTuile.hpp.
Referenced by addInventaire(), addItem(), getInventaire(), and interagirTuile().
The documentation for this class was generated from the following files:
src/model/MTuile.hpp
src/model/MTuile.cpp