A Space Story: CNiveau Class Reference
CNiveau Class Reference
#include <CNiveau.hpp>
Public Member Functions
CNiveau (AppFrameInterface *vuePrincipale, std::string levelFolder=MParameters::getMainScriptFolder(), std::string levelMainFile=MParameters::getMainScript())
virtual ~CNiveau ()
MEntite * getEntite (std::string name)
void addEntite (std::string name, std::string texture, MTuile *tuile, float taille)
void addEnigme (std::string nom, std::string description, std::string image)
void afficherEnigme (std::string nom)
MTerrain & getTerrain ()
void setScriptFolder (std::string levelFolder)
std::string getScriptFolder () const
void setLevelMainFile (std::string levelMainFile)
std::string getLevelMainFile () const
std::string getScript () const
Private Member Functions
void setEventMethods ()
Private Attributes
MTerrain terrain
AppFrameInterface * vuePrincipale
std::map< std::string, MEntite > entites
std::string levelFolder
std::string levelMainFile
std::map< std::string, VEnigma * > enigmes
Detailed Description
controleur pour les niveaux
Definition at line 31 of file CNiveau.hpp.
Constructor & Destructor Documentation
CNiveau()
CNiveau::CNiveau (AppFrameInterface * vuePrincipale, std::string levelFolder = MParameters::getMainScriptFolder(), std::string levelMainFile = MParameters::getMainScript())
Definition at line 31 of file CNiveau.cpp.
References setEventMethods(), and terrain.
~CNiveau()
CNiveau::~CNiveau () virtual
Definition at line 39 of file CNiveau.cpp.
References enigmes.
Member Function Documentation
addEnigme()
void CNiveau::addEnigme (std::string nom, std::string description, std::string image)
Definition at line 126 of file CNiveau.cpp.
References enigmes.
Referenced by CLua::cppNewEnigme().
addEntite()
void CNiveau::addEntite (std::string name, std::string texture, MTuile * tuile, float taille)
Definition at line 99 of file CNiveau.cpp.
References AppFrameInterface::addEntite(), entites, MTuile::getPosition(), AppFrameInterface::setPositionOf(), and vuePrincipale.
Referenced by CLua::cppNewEntity().
afficherEnigme()
void CNiveau::afficherEnigme (std::string nom)
Definition at line 134 of file CNiveau.cpp.
References enigmes.
Referenced by CLua::cppAfficherEnigme().
getEntite()
MEntite * CNiveau::getEntite (std::string name)
Definition at line 89 of file CNiveau.cpp.
References entites.
Referenced by CJeu::getEntite().
getLevelMainFile()
std::string CNiveau::getLevelMainFile () const
Definition at line 84 of file CNiveau.cpp.
References levelMainFile.
Referenced by CLua::cppGetScriptPath().
getScript()
std::string CNiveau::getScript () const
Returns
le chemin du script lua du niveau courrant
Definition at line 116 of file CNiveau.cpp.
References MParameters::getLevelPath(), levelFolder, and levelMainFile.
Referenced by CJeu::CJeu().
getScriptFolder()
std::string CNiveau::getScriptFolder () const
Definition at line 74 of file CNiveau.cpp.
References MParameters::getLevelPath(), and levelFolder.
Referenced by CLua::cppGetScriptPath(), CLua::cppLoadCouche(), and CLua::loadfile().
getTerrain()
MTerrain & CNiveau::getTerrain ()
Definition at line 121 of file CNiveau.cpp.
References terrain.
Referenced by CLua::cppAddActionMining(), CLua::cppLoadCouche(), and CLua::getTuile().
setEventMethods()
void CNiveau::setEventMethods () private
Definition at line 50 of file CNiveau.cpp.
References COUCHE_LOADED, ENTITY_MOVED, MTerrain::getImagesList(), MParameters::getTailleTuile(), MParameters::getTextureFor(), AppFrameInterface::loadFileIntoGround(), AppFrameInterface::setPositionOf(), terrain, and vuePrincipale.
Referenced by CNiveau().
setLevelMainFile()
void CNiveau::setLevelMainFile (std::string levelMainFile)
Definition at line 79 of file CNiveau.cpp.
References levelMainFile.
Referenced by CLua::cppSetScriptPath().
setScriptFolder()
void CNiveau::setScriptFolder (std::string levelFolder)
Definition at line 69 of file CNiveau.cpp.
References levelFolder.
Referenced by CLua::cppSetScriptPath().
Member Data Documentation
enigmes
std::map<std::string, VEnigma*> CNiveau::enigmes private
Definition at line 49 of file CNiveau.hpp.
Referenced by addEnigme(), afficherEnigme(), and ~CNiveau().
entites
std::map<std::string, MEntite> CNiveau::entites private
entité du niveau courant créer par le lua (sans les perso ni les robots)
Definition at line 40 of file CNiveau.hpp.
Referenced by addEntite(), and getEntite().
levelFolder
std::string CNiveau::levelFolder private
folder for level resources
Definition at line 44 of file CNiveau.hpp.
Referenced by getScript(), getScriptFolder(), and setScriptFolder().
levelMainFile
std::string CNiveau::levelMainFile private
main level script, executed to construct the level
Definition at line 48 of file CNiveau.hpp.
Referenced by getLevelMainFile(), getScript(), and setLevelMainFile().
terrain
MTerrain CNiveau::terrain private
Definition at line 35 of file CNiveau.hpp.
Referenced by CNiveau(), getTerrain(), and setEventMethods().
vuePrincipale
AppFrameInterface* CNiveau::vuePrincipale private
Definition at line 36 of file CNiveau.hpp.
Referenced by addEntite(), and setEventMethods().
The documentation for this class was generated from the following files:
src/controlleur/CNiveau.hpp
src/controlleur/CNiveau.cpp