A Space Story: MItem Class Reference
MItem Class Reference
#include <MItem.hpp>
Public Member Functions
MItem (std::string nom, std::string const &texture, std::string description, MTypeEquipement type=MTypeEquipement::MAIN, int degats=0, int protection=0, bool supprimable=true, int miningLevel=0)
void utilisation (MEntite *entite)
bool operator== (MItem const &other) const
std::string getNom () const
std::string getDescription () const
int getDegats () const
int getProtection () const
Id getId () const
void setActionUtilisation (std::function< void(std::string entite)> actionUtilisation)
MTypeEquipement getType () const
int getMiningLevel () const
Public Member Functions inherited from MObjetTexture
MObjetTexture (std::string texture)
virtual ~MObjetTexture ()
std::string getTexture ()
void setTexture (std::string texture)
Private Attributes
Id id
std::string nom
MTypeEquipement type
std::string description
int degats
int protection
bool supprimable
std::function< void(std::string entite)> actionUtilisation
int miningLevel
Static Private Attributes
static Id nextId = 0
Detailed Description
Definition at line 21 of file MItem.hpp.
Constructor & Destructor Documentation
MItem()
MItem::MItem (std::string nom, std::string const & texture, std::string description, MTypeEquipement type = MTypeEquipement::MAIN, int degats = 0, int protection = 0, bool supprimable = true, int miningLevel = 0)
Definition at line 19 of file MItem.cpp.
Member Function Documentation
getDegats()
int MItem::getDegats () const
Definition at line 28 of file MItem.cpp.
References degats.
getDescription()
std::string MItem::getDescription () const inline
Definition at line 68 of file MItem.hpp.
References description.
Referenced by MTuile::addItem().
getId()
Id MItem::getId () const
Definition at line 43 of file MItem.cpp.
References id.
Referenced by MTuile::addItem(), CLua::cppNewItem(), and operator==().
getMiningLevel()
int MItem::getMiningLevel () const inline
Definition at line 73 of file MItem.hpp.
References miningLevel.
Referenced by MEntite::getMiningPower().
getNom()
std::string MItem::getNom () const
Definition at line 38 of file MItem.cpp.
References nom.
Referenced by MTuile::addItem().
getProtection()
int MItem::getProtection () const
Definition at line 33 of file MItem.cpp.
References protection.
getType()
MTypeEquipement MItem::getType () const inline
Definition at line 63 of file MItem.hpp.
References type.
Referenced by MInventaire::equipe().
operator==()
bool MItem::operator== (MItem const & other) const
Definition at line 13 of file MItem.cpp.
References getId().
setActionUtilisation()
void MItem::setActionUtilisation (std::function< void(std::string entite)> actionUtilisation)
Definition at line 48 of file MItem.cpp.
References actionUtilisation.
Referenced by CLua::cppAddActionUtilisation().
utilisation()
void MItem::utilisation (MEntite * entite)
Definition at line 53 of file MItem.cpp.
References actionUtilisation, and MEntite::getNom().
Referenced by MEntite::utiliserObjet().
Member Data Documentation
actionUtilisation
std::function<void(std::string entite)> MItem::actionUtilisation private
Definition at line 34 of file MItem.hpp.
Referenced by setActionUtilisation(), and utilisation().
degats
int MItem::degats private
Definition at line 30 of file MItem.hpp.
Referenced by getDegats().
description
std::string MItem::description private
Definition at line 29 of file MItem.hpp.
Referenced by getDescription().
id
Id MItem::id private
Definition at line 25 of file MItem.hpp.
Referenced by getId().
miningLevel
int MItem::miningLevel private
Definition at line 35 of file MItem.hpp.
Referenced by getMiningLevel().
nextId
Id MItem::nextId = 0 static private
Definition at line 26 of file MItem.hpp.
nom
std::string MItem::nom private
Definition at line 27 of file MItem.hpp.
Referenced by getNom().
protection
int MItem::protection private
Definition at line 31 of file MItem.hpp.
Referenced by getProtection().
supprimable
bool MItem::supprimable private
Definition at line 32 of file MItem.hpp.
type
MTypeEquipement MItem::type private
Definition at line 28 of file MItem.hpp.
Referenced by getType().
The documentation for this class was generated from the following files:
src/model/MItem.hpp
src/model/MItem.cpp