A Space Story: VPlayerInventory Class Reference
VPlayerInventory Class Reference
#include <VPlayerInventory.hpp>
Public Member Functions
VPlayerInventory (wxString const &title, MCoordonnees coord)
~VPlayerInventory ()
void addObjPlayerQuickInv (unsigned long long id, std::string name, std::string description, std::string image, int position=-1) override
void delObjInv (unsigned long long id)
Public Member Functions inherited from VPlayerInventaireInterface
VPlayerInventaireInterface (MCoordonnees const &size)
virtual ~VPlayerInventaireInterface ()=default
Public Member Functions inherited from VInventaireInterface
VInventaireInterface (MCoordonnees const &size)
virtual ~VInventaireInterface ()=default
Public Member Functions inherited from VInventory
VInventory (wxString const &title, MCoordonnees coord)
virtual ~VInventory ()
void addObjInv (unsigned long long id, std::string name, std::string description, std::string image, int position=-1) override
void show (bool show=true) override
Private Attributes
std::vector< VItem * > Quick
Detailed Description
Definition at line 13 of file VPlayerInventory.hpp.
Constructor & Destructor Documentation
VPlayerInventory()
VPlayerInventory::VPlayerInventory (wxString const & title, MCoordonnees coord)
Definition at line 29 of file VPlayerInventory.cpp.
~VPlayerInventory()
VPlayerInventory::~VPlayerInventory ()
Definition at line 35 of file VPlayerInventory.cpp.
Member Function Documentation
addObjPlayerQuickInv()
void VPlayerInventory::addObjPlayerQuickInv (unsigned long long id, std::string name, std::string description, std::string image, int position = -1) override virtual
Parameters
id id de l'objet
image image de l'objet
position la position dans l'inventaire ligne par ligne, si -1 l'objet va dans la première case disponible
Implements VPlayerInventaireInterface.
Definition at line 40 of file VPlayerInventory.cpp.
References VItem::LoadImage(), Quick, VItem::setDescription(), and VItem::setID().
delObjInv()
void VPlayerInventory::delObjInv (unsigned long long id) virtual
Reimplemented from VInventory.
Definition at line 72 of file VPlayerInventory.cpp.
References VInventory::delObjInv(), and Quick.
Member Data Documentation
Quick
std::vector<VItem*> VPlayerInventory::Quick private
Definition at line 17 of file VPlayerInventory.hpp.
Referenced by addObjPlayerQuickInv(), and delObjInv().
The documentation for this class was generated from the following files:
src/vue/VPlayerInventory.hpp
src/vue/VPlayerInventory.cpp