A Space Story: wxSfmlCanvas Class Reference
wxSfmlCanvas Class Reference
#include <wxSFMLCanevas.hpp>
Public Member Functions
wxSfmlCanvas (wxWindow *parent=nullptr, wxWindowID windowId=-1, wxPoint const &position=wxDefaultPosition, wxSize const &size=wxDefaultSize, long style=0)
virtual void onUpdate ()
wxDECLARE_EVENT_TABLE ()
void onIdle (wxIdleEvent &event)
void onPaint (wxPaintEvent &event)
void onEraseBackground (wxEraseEvent &event)
void createRenderWindow ()
void setwxWindowSize (wxSize const &size)
void setRenderWindowSize (sf::Vector2u const &size)
virtual ~wxSfmlCanvas ()
Detailed Description
Definition at line 17 of file wxSFMLCanevas.hpp.
Constructor & Destructor Documentation
wxSfmlCanvas()
wxSfmlCanvas::wxSfmlCanvas (wxWindow * parent = nullptr, wxWindowID windowId = -1, wxPoint const & position = wxDefaultPosition, wxSize const & size = wxDefaultSize, long style = 0)
Definition at line 10 of file wxSFMLCaneva.cpp.
References createRenderWindow().
~wxSfmlCanvas()
wxSfmlCanvas::~wxSfmlCanvas () virtual
Definition at line 59 of file wxSFMLCaneva.cpp.
References onEraseBackground(), onIdle(), and onPaint().
Member Function Documentation
createRenderWindow()
void wxSfmlCanvas::createRenderWindow ()
Definition at line 37 of file wxSFMLCaneva.cpp.
Referenced by wxSfmlCanvas().
onEraseBackground()
void wxSfmlCanvas::onEraseBackground (wxEraseEvent & event)
Definition at line 33 of file wxSFMLCaneva.cpp.
Referenced by ~wxSfmlCanvas().
onIdle()
void wxSfmlCanvas::onIdle (wxIdleEvent & event)
Definition at line 21 of file wxSFMLCaneva.cpp.
Referenced by ~wxSfmlCanvas().
onPaint()
void wxSfmlCanvas::onPaint (wxPaintEvent & event)
Definition at line 27 of file wxSFMLCaneva.cpp.
References onUpdate().
Referenced by ~wxSfmlCanvas().
onUpdate()
void wxSfmlCanvas::onUpdate () virtual
Reimplemented in Canvas.
Definition at line 17 of file wxSFMLCaneva.cpp.
Referenced by onPaint().
setRenderWindowSize()
void wxSfmlCanvas::setRenderWindowSize (sf::Vector2u const & size)
Definition at line 55 of file wxSFMLCaneva.cpp.
setwxWindowSize()
void wxSfmlCanvas::setwxWindowSize (wxSize const & size)
Definition at line 51 of file wxSFMLCaneva.cpp.
wxDECLARE_EVENT_TABLE()
wxSfmlCanvas::wxDECLARE_EVENT_TABLE ()
The documentation for this class was generated from the following files:
src/vue/wxSFMLCanevas.hpp
src/vue/wxSFMLCaneva.cpp