A Space Story: MCoordonnees Class Reference
MCoordonnees Class Reference
#include <MCoordonnees.hpp>
Public Member Functions
MCoordonnees (int x, int y)
MCoordonnees operator+ (MCoordonnees const &other) const
MCoordonnees const & operator= (MCoordonnees const &other)
MCoordonnees const & operator+= (MCoordonnees const &other)
bool operator== (MCoordonnees const &other) const
void deplacerDe (MCoordonnees const &m)
int getX () const
int getY () const
std::string str () const
Private Attributes
int x
int y
Detailed Description
Definition at line 15 of file MCoordonnees.hpp.
Constructor & Destructor Documentation
MCoordonnees()
MCoordonnees::MCoordonnees (int x, int y)
Parameters
x
y
Definition at line 19 of file MCoordonnees.cpp.
Referenced by MouvementT::getDirectionCoords(), MouvementT::operator*(), and operator+().
Member Function Documentation
deplacerDe()
void MCoordonnees::deplacerDe (MCoordonnees const & m)
Definition at line 46 of file MCoordonnees.cpp.
getX()
int MCoordonnees::getX () const inline
Definition at line 78 of file MCoordonnees.hpp.
References x.
Referenced by MTerrain::loadCouche(), Canvas::move(), MTerrain::operator()(), Canvas::setPositionOf(), VPrimitif::show(), and MTerrain::toCoords().
getY()
int MCoordonnees::getY () const inline
Definition at line 83 of file MCoordonnees.hpp.
References y.
Referenced by MTerrain::loadCouche(), Canvas::move(), MTerrain::operator()(), and Canvas::setPositionOf().
operator+()
MCoordonnees MCoordonnees::operator+ (MCoordonnees const & other) const
Definition at line 24 of file MCoordonnees.cpp.
References MCoordonnees(), x, and y.
operator+=()
MCoordonnees const & MCoordonnees::operator+= (MCoordonnees const & other)
Definition at line 36 of file MCoordonnees.cpp.
operator=()
MCoordonnees const & MCoordonnees::operator= (MCoordonnees const & other)
Definition at line 29 of file MCoordonnees.cpp.
References x, and y.
operator==()
bool MCoordonnees::operator== (MCoordonnees const & other) const
Definition at line 41 of file MCoordonnees.cpp.
References x, and y.
str()
std::string MCoordonnees::str () const
Definition at line 51 of file MCoordonnees.cpp.
References to_string(), x, and y.
Referenced by MExceptionEntiteNonPresente::what().
Member Data Documentation
x
int MCoordonnees::x private
Definition at line 34 of file MCoordonnees.hpp.
Referenced by getX(), operator+(), operator=(), operator==(), and str().
y
int MCoordonnees::y private
Definition at line 35 of file MCoordonnees.hpp.
Referenced by getY(), operator+(), operator=(), operator==(), and str().
The documentation for this class was generated from the following files:
src/model/MCoordonnees.hpp
src/model/MCoordonnees.cpp