A Space Story: wxImagePanel Class Reference
wxImagePanel Class Reference
#include <ImagePanel.hpp>
Public Member Functions
wxImagePanel (wxFrame *parent, wxString file, wxBitmapType format)
wxSize getPictureSize ()
void paintEvent (wxPaintEvent &evt)
void paintNow ()
void OnSize (wxSizeEvent &event)
void render (wxDC &dc)
virtual void LoadImage (std::string file)
Private Attributes
wxBitmap image
wxBitmap resized
int w
int h
Detailed Description
Definition at line 12 of file ImagePanel.hpp.
Constructor & Destructor Documentation
wxImagePanel()
wxImagePanel::wxImagePanel (wxFrame * parent, wxString file, wxBitmapType format)
Definition at line 10 of file ImagePanel.cpp.
References h, image, OnSize(), paintEvent(), and w.
Member Function Documentation
getPictureSize()
wxSize wxImagePanel::getPictureSize ()
Definition at line 84 of file ImagePanel.cpp.
References image.
Referenced by VEnigma::VEnigma().
LoadImage()
void wxImagePanel::LoadImage (std::string file) virtual
Reimplemented in VItem.
Definition at line 89 of file ImagePanel.cpp.
References image.
Referenced by VItem::LoadImage().
OnSize()
void wxImagePanel::OnSize (wxSizeEvent & event)
Definition at line 77 of file ImagePanel.cpp.
Referenced by wxImagePanel().
paintEvent()
void wxImagePanel::paintEvent (wxPaintEvent & evt)
Definition at line 28 of file ImagePanel.cpp.
References render().
Referenced by wxImagePanel().
paintNow()
void wxImagePanel::paintNow ()
Definition at line 43 of file ImagePanel.cpp.
References render().
render()
void wxImagePanel::render (wxDC & dc)
Definition at line 55 of file ImagePanel.cpp.
References h, image, resized, and w.
Referenced by paintEvent(), and paintNow().
Member Data Documentation
h
int wxImagePanel::h private
Definition at line 16 of file ImagePanel.hpp.
Referenced by render(), and wxImagePanel().
image
wxBitmap wxImagePanel::image private
Definition at line 14 of file ImagePanel.hpp.
Referenced by getPictureSize(), LoadImage(), render(), and wxImagePanel().
resized
wxBitmap wxImagePanel::resized private
Definition at line 15 of file ImagePanel.hpp.
Referenced by render().
w
int wxImagePanel::w private
Definition at line 16 of file ImagePanel.hpp.
Referenced by render(), and wxImagePanel().
The documentation for this class was generated from the following files:
src/vue/ImagePanel.hpp
src/vue/ImagePanel.cpp