A Space Story: AppFrameInterface Class Reference
AppFrameInterface Class Reference abstract
#include <AppFrameInterface.hpp>
Public Member Functions
AppFrameInterface ()=default
virtual ~AppFrameInterface ()=default
virtual void loadFileIntoGround (int const *idList, std::string texture, MTypeCouche level, int tailleTexture)=0
virtual void addEntite (std::string entityName, std::string file)=0
virtual void move (std::string entityName, MCoordonnees const &offset, Mouvement direction)=0
virtual void setPositionOf (std::string entityName, MCoordonnees const &position, Mouvement direction)=0
virtual void parler (std::string entityTexture, std::string parole)=0
Detailed Description
interface pour contrôleur <-> vue
Definition at line 22 of file AppFrameInterface.hpp.
Constructor & Destructor Documentation
AppFrameInterface()
AppFrameInterface::AppFrameInterface () default
~AppFrameInterface()
virtual AppFrameInterface::~AppFrameInterface () virtual default
Member Function Documentation
addEntite()
virtual void AppFrameInterface::addEntite (std::string entityName, std::string file) pure virtual
Implemented in AppFrame.
Referenced by CNiveau::addEntite(), CPersonnage::addRobot(), and CJeu::CJeu().
loadFileIntoGround()
virtual void AppFrameInterface::loadFileIntoGround (int const * idList, std::string texture, MTypeCouche level, int tailleTexture) pure virtual
Implemented in AppFrame.
Referenced by CPersonnage::setEventMethods(), and CNiveau::setEventMethods().
move()
virtual void AppFrameInterface::move (std::string entityName, MCoordonnees const & offset, Mouvement direction) pure virtual
Implemented in AppFrame.
parler()
virtual void AppFrameInterface::parler (std::string entityTexture, std::string parole) pure virtual
Implemented in AppFrame.
Referenced by CLua::cppParler().
setPositionOf()
virtual void AppFrameInterface::setPositionOf (std::string entityName, MCoordonnees const & position, Mouvement direction) pure virtual
Implemented in AppFrame.
Referenced by CNiveau::addEntite(), CPersonnage::addRobot(), CJeu::CJeu(), CPersonnage::setEventMethods(), and CNiveau::setEventMethods().
The documentation for this class was generated from the following file:
src/vue/AppFrameInterface.hpp