A Space Story: VPrimitif Class Reference
VPrimitif Class Reference
#include <VPrimitif.hpp>
Public Member Functions
VPrimitif (MCoordonnees const &coordMax)
virtual ~VPrimitif ()
void show (MCoordonnees positionJoueur)
void setImg (MTypeCouche const &typeCouche, std::vector< std::string const *> const &imgs)
Private Member Functions
void printTile (char type)
void sendInput ()
Private Attributes
MCoordonnees const TAILLE_MAX
std::vector< std::string const * > imgSols
std::vector< std::string const * > imgElems
std::vector< std::string const * > imgCiels
Static Private Attributes
static char constexpr perso = '*'
static char constexpr terrainHerbe = '.'
static char constexpr montagne = '#'
static std::string const escC = "\e["
static std::string const endC = "m"
static std::string const sepC = ";"
static std::string const foregroundRgb = "38;2;"
static std::string const blanc = escC + "0" + endC
static std::map< char, std::string > const colors
Detailed Description
Definition at line 22 of file VPrimitif.hpp.
Constructor & Destructor Documentation
VPrimitif()
VPrimitif::VPrimitif (MCoordonnees const & coordMax)
Definition at line 41 of file VPrimitif.cpp.
~VPrimitif()
VPrimitif::~VPrimitif () virtual
Definition at line 47 of file VPrimitif.cpp.
Member Function Documentation
printTile()
void VPrimitif::printTile (char type) private
Definition at line 68 of file VPrimitif.cpp.
References blanc, and colors.
Referenced by show().
sendInput()
void VPrimitif::sendInput () private
Definition at line 117 of file VPrimitif.cpp.
References clear(), and KEY_PRESSED.
Referenced by show().
setImg()
void VPrimitif::setImg (MTypeCouche const & typeCouche, std::vector< std::string const *> const & imgs)
Definition at line 126 of file VPrimitif.cpp.
References CIEL, ELEMENT, imgCiels, imgElems, imgSols, and SOL.
show()
void VPrimitif::show (MCoordonnees positionJoueur)
Definition at line 80 of file VPrimitif.cpp.
References clearScreen(), MCoordonnees::getX(), imgSols, perso, printTile(), sendInput(), and TAILLE_MAX.
Member Data Documentation
blanc
std::string const VPrimitif::blanc = escC + "0" + endC static private
Definition at line 36 of file VPrimitif.hpp.
Referenced by printTile().
colors
std::map< char, std::string > const VPrimitif::colors static private
Initial value:
= { { '.', escC + "32" + endC }, { '#',
    escC + foregroundRgb + "107;73;54" + endC }, { '~', escC + "34" + endC }, { '=', escC
    + foregroundRgb + "107;73;74" + endC } }
Definition at line 38 of file VPrimitif.hpp.
Referenced by printTile().
endC
std::string const VPrimitif::endC = "m" static private
Definition at line 32 of file VPrimitif.hpp.
escC
std::string const VPrimitif::escC = "\e[" static private
Definition at line 31 of file VPrimitif.hpp.
foregroundRgb
std::string const VPrimitif::foregroundRgb = "38;2;" static private
Definition at line 34 of file VPrimitif.hpp.
imgCiels
std::vector<std::string const*> VPrimitif::imgCiels private
Definition at line 42 of file VPrimitif.hpp.
Referenced by setImg().
imgElems
std::vector<std::string const*> VPrimitif::imgElems private
Definition at line 41 of file VPrimitif.hpp.
Referenced by setImg().
imgSols
std::vector<std::string const*> VPrimitif::imgSols private
Definition at line 40 of file VPrimitif.hpp.
Referenced by setImg(), and show().
montagne
char constexpr VPrimitif::montagne = '#' static private
Definition at line 28 of file VPrimitif.hpp.
perso
char constexpr VPrimitif::perso = '*' static private
Definition at line 26 of file VPrimitif.hpp.
Referenced by show().
sepC
std::string const VPrimitif::sepC = ";" static private
Definition at line 33 of file VPrimitif.hpp.
TAILLE_MAX
MCoordonnees const VPrimitif::TAILLE_MAX private
Definition at line 29 of file VPrimitif.hpp.
Referenced by show().
terrainHerbe
char constexpr VPrimitif::terrainHerbe = '.' static private
Definition at line 27 of file VPrimitif.hpp.
The documentation for this class was generated from the following files:
src/vue/VPrimitif.hpp
src/vue/VPrimitif.cpp