A Space Story: MRobot Class Reference
MRobot Class Reference
#include <MRobot.hpp>
Public Member Functions
MRobot (MPersonnage *proprietaire, std::string const &texture, std::string const &nom, MTuile *tuile, float taille)
virtual ~MRobot ()
bool launch ()
bool reset ()
bool isReset ()
std::chrono::milliseconds const & getSpeed () const
MTuile const * getBeginPos () const
Public Member Functions inherited from MEntite
MEntite (std::string const &nom, std::string const &texture, MTuile *tuile=nullptr, float taille=1)
virtual ~MEntite ()
void deplacer (MTerrain &terrain, Mouvement const &deplacement)
void attaquer (MTerrain &terrain)
void seDefendre (MEntite &attaquant, int degats)
void interagirTuile (MTerrain &terrain)
void interagirEntite (MTerrain &terrain)
void utiliserObjet ()
void mine (MTerrain &terrain)
int defenseTotale () const
int forceTotale () const
void addItemToInventaire (MItem *item)
void equipe (Id idItem)
Mouvement getDirection () const
void setDirection (Mouvement direction)
std::string const & getNom () const
MTuile const * getTuile () const
void setTuile (MTuile *tuile)
float getTaille () const
void setTaille (float taille)
MCompetence const & getCompetences () const
MInventaire & getInventaire ()
void setActionDefense (std::function< void(std::string entite, int degat)> actionDefense)
void setActionInteraction (std::function< void(MEntite const &entite)> actionInteraction)
Public Member Functions inherited from MObjetTexture
MObjetTexture (std::string texture)
virtual ~MObjetTexture ()
std::string getTexture ()
void setTexture (std::string texture)
Private Member Functions
void setSpeed (std::chrono::milliseconds const &speed)
Private Attributes
MPersonnage & proprietaire
std::chrono::milliseconds speed
MTuile * posDepart
Mouvement dirDepart
Detailed Description
Nothing special, maybe some specific behavior is becoming later
Definition at line 27 of file MRobot.hpp.
Constructor & Destructor Documentation
MRobot()
MRobot::MRobot (MPersonnage * proprietaire, std::string const & texture, std::string const & nom, MTuile * tuile, float taille)
Definition at line 29 of file MRobot.cpp.
~MRobot()
MRobot::~MRobot () virtual
Definition at line 36 of file MRobot.cpp.
Member Function Documentation
getBeginPos()
MTuile const * MRobot::getBeginPos () const inline
Definition at line 68 of file MRobot.hpp.
References posDepart.
getSpeed()
std::chrono::milliseconds const & MRobot::getSpeed () const inline
Definition at line 63 of file MRobot.hpp.
References speed.
isReset()
bool MRobot::isReset ()
Definition at line 65 of file MRobot.cpp.
References dirDepart, MEntite::getDirection(), MTuile::getPosition(), MEntite::getTuile(), and posDepart.
Referenced by reset().
launch()
bool MRobot::launch ()
Definition at line 43 of file MRobot.cpp.
References reset().
reset()
bool MRobot::reset ()
Definition at line 48 of file MRobot.cpp.
References dirDepart, ENTITY_MOVED, isReset(), posDepart, MEntite::setDirection(), and MEntite::setTuile().
Referenced by launch().
setSpeed()
void MRobot::setSpeed (std::chrono::milliseconds const & speed) inline private
Definition at line 73 of file MRobot.hpp.
References speed.
Member Data Documentation
dirDepart
Mouvement MRobot::dirDepart private
Definition at line 34 of file MRobot.hpp.
Referenced by isReset(), and reset().
posDepart
MTuile* MRobot::posDepart private
Definition at line 33 of file MRobot.hpp.
Referenced by getBeginPos(), isReset(), and reset().
proprietaire
MPersonnage& MRobot::proprietaire private
Definition at line 31 of file MRobot.hpp.
speed
std::chrono::milliseconds MRobot::speed private
Definition at line 32 of file MRobot.hpp.
Referenced by getSpeed(), and setSpeed().
The documentation for this class was generated from the following files:
src/model/MRobot.hpp
src/model/MRobot.cpp