A Space Story: VInventory Class Reference
VInventory Class Reference
#include <VInventory.hpp>
Public Member Functions
VInventory (wxString const &title, MCoordonnees coord)
virtual ~VInventory ()
void addObjInv (unsigned long long id, std::string name, std::string description, std::string image, int position=-1) override
void delObjInv (unsigned long long id) override
void show (bool show=true) override
Public Member Functions inherited from VInventaireInterface
VInventaireInterface (MCoordonnees const &size)
virtual ~VInventaireInterface ()=default
Private Attributes
std::vector< VItem * > items
Detailed Description
Definition at line 14 of file VInventory.hpp.
Constructor & Destructor Documentation
VInventory()
VInventory::VInventory (wxString const & title, MCoordonnees coord)
Definition at line 19 of file VInventory.cpp.
References MCoordonnees::getX(), MCoordonnees::getY(), and items.
~VInventory()
VInventory::~VInventory () virtual
Definition at line 50 of file VInventory.cpp.
Member Function Documentation
addObjInv()
void VInventory::addObjInv (unsigned long long id, std::string name, std::string description, std::string image, int position = -1) override virtual
Parameters
id id de l'objet
image image de l'objet
position la position dans l'inventaire ligne par ligne, si -1 l'objet va dans la première case disponible
Implements VInventaireInterface.
Definition at line 56 of file VInventory.cpp.
References items, VItem::LoadImage(), VItem::setDescription(), and VItem::setID().
delObjInv()
void VInventory::delObjInv (unsigned long long id) override virtual
Implements VInventaireInterface.
Reimplemented in VPlayerInventory.
Definition at line 88 of file VInventory.cpp.
References items.
Referenced by VPlayerInventory::delObjInv().
show()
void VInventory::show (bool show = true) override virtual
Implements VInventaireInterface.
Definition at line 104 of file VInventory.cpp.
Member Data Documentation
items
std::vector<VItem*> VInventory::items private
Definition at line 18 of file VInventory.hpp.
Referenced by addObjInv(), delObjInv(), and VInventory().
The documentation for this class was generated from the following files:
src/vue/VInventory.hpp
src/vue/VInventory.cpp