A Space Story: VItem Class Reference
VItem Class Reference
#include <VItem.hpp>
Public Member Functions
VItem (wxFrame *parent, wxString file, wxBitmapType format, std::string nom="hitler", std::string description="dictateur allemand", unsigned long long int ID=1)
virtual ~VItem ()
std::string getNom ()
std::string getDescription ()
unsigned long long int getID ()
std::string getFile ()
void setNom (std::string nom)
void setDescription (std::string description)
void setID (unsigned long long int ID)
void setFile (std::string file)
void LoadImage (std::string file) override
Public Member Functions inherited from wxImagePanel
wxImagePanel (wxFrame *parent, wxString file, wxBitmapType format)
wxSize getPictureSize ()
void paintEvent (wxPaintEvent &evt)
void paintNow ()
void OnSize (wxSizeEvent &event)
void render (wxDC &dc)
Private Attributes
std::string nom
std::string description
unsigned long long int ID
std::string file
Detailed Description
Definition at line 17 of file VItem.hpp.
Constructor & Destructor Documentation
VItem()
VItem::VItem (wxFrame * parent, wxString file, wxBitmapType format, std::string nom = "hitler", std::string description = "dictateur allemand", unsigned long long int ID = 1)
Definition at line 18 of file VItem.cpp.
~VItem()
VItem::~VItem () virtual
Definition at line 72 of file VItem.cpp.
Member Function Documentation
getDescription()
std::string VItem::getDescription ()
Definition at line 30 of file VItem.cpp.
References description.
getFile()
std::string VItem::getFile ()
Definition at line 40 of file VItem.cpp.
References file.
getID()
unsigned long long int VItem::getID ()
Definition at line 35 of file VItem.cpp.
References ID.
getNom()
std::string VItem::getNom ()
Definition at line 25 of file VItem.cpp.
References nom.
LoadImage()
void VItem::LoadImage (std::string file) override virtual
Reimplemented from wxImagePanel.
Definition at line 66 of file VItem.cpp.
References wxImagePanel::LoadImage(), and setFile().
Referenced by VInventory::addObjInv(), and VPlayerInventory::addObjPlayerQuickInv().
setDescription()
void VItem::setDescription (std::string description)
Definition at line 50 of file VItem.cpp.
References description.
Referenced by VInventory::addObjInv(), and VPlayerInventory::addObjPlayerQuickInv().
setFile()
void VItem::setFile (std::string file)
Definition at line 60 of file VItem.cpp.
References file.
Referenced by LoadImage().
setID()
void VItem::setID (unsigned long long int ID)
Definition at line 55 of file VItem.cpp.
References ID.
Referenced by VInventory::addObjInv(), and VPlayerInventory::addObjPlayerQuickInv().
setNom()
void VItem::setNom (std::string nom)
Definition at line 45 of file VItem.cpp.
References nom.
Member Data Documentation
description
std::string VItem::description private
Definition at line 22 of file VItem.hpp.
Referenced by getDescription(), and setDescription().
file
std::string VItem::file private
Definition at line 24 of file VItem.hpp.
Referenced by getFile(), and setFile().
ID
unsigned long long int VItem::ID private
Definition at line 23 of file VItem.hpp.
Referenced by getID(), and setID().
nom
std::string VItem::nom private
Definition at line 21 of file VItem.hpp.
Referenced by getNom(), and setNom().
The documentation for this class was generated from the following files:
src/vue/VItem.hpp
src/vue/VItem.cpp