A Space Story: MThreads Class Reference
MThreads Class Reference
#include <MThreads.hpp>
Static Public Member Functions
template<class fct , class ... Args>
static void parallelize (fct &&function, Args &&... args)
Static Private Member Functions
template<typename R >
static bool is_ready (std::future< R > const &f)
Static Private Attributes
static std::future< void > thread1
static std::future< void > thread2
Detailed Description
Definition at line 16 of file MThreads.hpp.
Member Function Documentation
is_ready()
template<typename R > static bool MThreads::is_ready (std::future< R > const & f) inline static private
Definition at line 49 of file MThreads.hpp.
Referenced by parallelize().
parallelize()
template<class fct , class ... Args> static void MThreads::parallelize (fct && function, Args &&... args) inline static
Definition at line 30 of file MThreads.hpp.
References is_ready().
Referenced by MPartieCouche::declenchementDe(), MEntite::interagirEntite(), MPartieCoucheElement::mine(), MPartieCouche::passageDe(), and MEntite::seDefendre().
Member Data Documentation
thread1
std::future< void > MThreads::thread1 static private
Definition at line 20 of file MThreads.hpp.
thread2
std::future< void > MThreads::thread2 static private
Definition at line 21 of file MThreads.hpp.
The documentation for this class was generated from the following files:
src/model/MThreads.hpp
src/model/MThreads.cpp