A Space Story: VInventaireInterface Class Reference
VInventaireInterface Class Reference abstract
#include <VInventaireInterface.hpp>
Public Member Functions
VInventaireInterface (MCoordonnees const &size)
virtual ~VInventaireInterface ()=default
virtual void addObjInv (unsigned long long id, std::string name, std::string description, std::string image, int position=-1)=0
virtual void delObjInv (unsigned long long id)=0
virtual void show (bool show=true)=0
Private Attributes
MCoordonnees size
Detailed Description
Definition at line 17 of file VInventaireInterface.hpp.
Constructor & Destructor Documentation
VInventaireInterface()
VInventaireInterface::VInventaireInterface (MCoordonnees const & size) inline
Parameters
size définie la taille de l'inventaire, et aussi le x définie la taille du quickInventaire\ Il y a donc x*(y+1) cases\
eg : x = 3, y = 2, il y a au total 3*(2+1) cases\ □□□ // inventaire □□□
□□□ // barre d'inventaire rapide
Definition at line 36 of file VInventaireInterface.hpp.
References addObjInv(), delObjInv(), show(), and ~VInventaireInterface().
~VInventaireInterface()
virtual VInventaireInterface::~VInventaireInterface () virtual default
Referenced by VInventaireInterface().
Member Function Documentation
addObjInv()
virtual void VInventaireInterface::addObjInv (unsigned long long id, std::string name, std::string description, std::string image, int position = -1) pure virtual
Parameters
id id de l'objet
image image de l'objet
position la position dans l'inventaire ligne par ligne, si -1 l'objet va dans la première case disponible
Implemented in VInventory.
Referenced by MTuile::addItem(), and VInventaireInterface().
delObjInv()
virtual void VInventaireInterface::delObjInv (unsigned long long id) pure virtual
Implemented in VPlayerInventory, and VInventory.
Referenced by VInventaireInterface().
show()
virtual void VInventaireInterface::show (bool show = true) pure virtual
Implemented in VInventory.
Referenced by CLua::cppShowInventory(), MTuile::interagirTuile(), and VInventaireInterface().
Member Data Documentation
size
MCoordonnees VInventaireInterface::size private
Definition at line 21 of file VInventaireInterface.hpp.
The documentation for this class was generated from the following file:
src/vue/VInventaireInterface.hpp