A Space Story: VEnigma Class Reference
VEnigma Class Reference
#include <VEnigma.hpp>
Public Member Functions
VEnigma (wxString const &title, wxString file, std::string text)
virtual ~VEnigma ()
void onFocus (wxFocusEvent &event)
void onQuit (wxCommandEvent &WXUNUSED(event))
Private Attributes
wxImagePanel * picture
wxTextCtrl * text
Detailed Description
Definition at line 12 of file VEnigma.hpp.
Constructor & Destructor Documentation
VEnigma()
VEnigma::VEnigma (wxString const & title, wxString file, std::string text)
Definition at line 18 of file VEnigma.cpp.
References wxImagePanel::getPictureSize(), onQuit(), picture, and text.
~VEnigma()
VEnigma::~VEnigma () virtual
Definition at line 41 of file VEnigma.cpp.
References picture, and text.
Member Function Documentation
onFocus()
void VEnigma::onFocus (wxFocusEvent & event)
onQuit()
void VEnigma::onQuit (wxCommandEvent & WXUNUSEDevent)
Definition at line 47 of file VEnigma.cpp.
Referenced by VEnigma().
Member Data Documentation
picture
wxImagePanel* VEnigma::picture private
Definition at line 16 of file VEnigma.hpp.
Referenced by VEnigma(), and ~VEnigma().
text
wxTextCtrl* VEnigma::text private
Definition at line 17 of file VEnigma.hpp.
Referenced by VEnigma(), and ~VEnigma().
The documentation for this class was generated from the following files:
src/vue/VEnigma.hpp
src/vue/VEnigma.cpp