A Space Story: Canvas Class Reference
Canvas Class Reference
#include <Caneva.hpp>
Public Member Functions
Canvas (wxWindow *parent, wxWindowID id, wxPoint position, wxSize size, long style=0, int TailleTexture=32)
virtual ~Canvas ()
virtual void onUpdate ()
std::map< std::string, sf::Sprite > & getSprites ()
void loadFileIntoGround (int const *idList, std::string texture, int level, int tailleTexture)
void drawAll ()
void fermer ()
bool setEvent ()
void addEntite (std::string name, std::string file)
void move (std::string entityName, MCoordonnees const &offset, Mouvement direction)
void setPositionOf (std::string entityName, MCoordonnees const &position, Mouvement direction)
void SetSize (int width, int height)
Public Member Functions inherited from wxSfmlCanvas
wxSfmlCanvas (wxWindow *parent=nullptr, wxWindowID windowId=-1, wxPoint const &position=wxDefaultPosition, wxSize const &size=wxDefaultSize, long style=0)
wxDECLARE_EVENT_TABLE ()
void onIdle (wxIdleEvent &event)
void onPaint (wxPaintEvent &event)
void onEraseBackground (wxEraseEvent &event)
void createRenderWindow ()
void setwxWindowSize (wxSize const &size)
void setRenderWindowSize (sf::Vector2u const &size)
virtual ~wxSfmlCanvas ()
Private Member Functions
void onResize (wxSizeEvent &event)
void onCursor (wxMouseEvent &event)
TileMap & getGround ()
TileMap & getObj ()
TileMap & getSky ()
void setTailleTexture (int taille)
int getTailleTexture ()
sf::Texture * getTexture (int index)
void setTexture (std::string const &file)
Private Attributes
TileMap ground
TileMap obj
TileMap sky
int x
int y
std::vector< sf::Texture * > textures
std::map< std::string, sf::Sprite > sprites
int tailleTexture
Detailed Description
Definition at line 24 of file Caneva.hpp.
Constructor & Destructor Documentation
Canvas()
Canvas::Canvas (wxWindow * parent, wxWindowID id, wxPoint position, wxSize size, long style = 0, int TailleTexture = 32)
Definition at line 23 of file Caneva.cpp.
References onCursor(), onResize(), tailleTexture, x, and y.
~Canvas()
Canvas::~Canvas () virtual
Definition at line 48 of file Caneva.cpp.
References textures.
Member Function Documentation
addEntite()
void Canvas::addEntite (std::string name, std::string file)
Definition at line 171 of file Caneva.cpp.
References getTexture(), setTexture(), sprites, and textures.
Referenced by AppFrame::addEntite().
drawAll()
void Canvas::drawAll ()
Definition at line 246 of file Caneva.cpp.
References clear(), ground, obj, sky, and sprites.
Referenced by loadFileIntoGround(), move(), onResize(), onUpdate(), setPositionOf(), and SetSize().
fermer()
void Canvas::fermer ()
Definition at line 143 of file Caneva.cpp.
getGround()
TileMap & Canvas::getGround () private
Definition at line 128 of file Caneva.cpp.
References ground.
getObj()
TileMap & Canvas::getObj () private
Definition at line 133 of file Caneva.cpp.
References obj.
getSky()
TileMap & Canvas::getSky () private
Definition at line 138 of file Caneva.cpp.
References sky.
getSprites()
std::map< std::string, sf::Sprite > & Canvas::getSprites ()
Definition at line 263 of file Caneva.cpp.
References sprites.
Referenced by move(), and setPositionOf().
getTailleTexture()
int Canvas::getTailleTexture () private
Definition at line 222 of file Caneva.cpp.
References tailleTexture.
Referenced by move(), and setPositionOf().
getTexture()
sf::Texture * Canvas::getTexture (int index) private
Definition at line 241 of file Caneva.cpp.
References textures.
Referenced by addEntite(), and setTexture().
loadFileIntoGround()
void Canvas::loadFileIntoGround (int const * idList, std::string texture, int level, int tailleTexture)
Definition at line 110 of file Caneva.cpp.
References drawAll(), ground, TileMap::load(), obj, sky, x, and y.
Referenced by AppFrame::loadFileIntoGround().
move()
void Canvas::move (std::string entityName, MCoordonnees const & offset, Mouvement direction)
Definition at line 181 of file Caneva.cpp.
References drawAll(), getSprites(), getTailleTexture(), MCoordonnees::getX(), and MCoordonnees::getY().
Referenced by AppFrame::move().
onCursor()
void Canvas::onCursor (wxMouseEvent & event) private
Definition at line 61 of file Caneva.cpp.
References MParameters::getNbTuileX(), MParameters::getNbTuileY(), and to_string().
Referenced by Canvas().
onResize()
void Canvas::onResize (wxSizeEvent & event) private
Definition at line 93 of file Caneva.cpp.
References drawAll(), x, and y.
Referenced by Canvas().
onUpdate()
void Canvas::onUpdate () virtual
Reimplemented from wxSfmlCanvas.
Definition at line 56 of file Caneva.cpp.
References drawAll().
setEvent()
bool Canvas::setEvent ()
Definition at line 149 of file Caneva.cpp.
setPositionOf()
void Canvas::setPositionOf (std::string entityName, MCoordonnees const & position, Mouvement direction)
Definition at line 200 of file Caneva.cpp.
References drawAll(), getSprites(), getTailleTexture(), MCoordonnees::getX(), and MCoordonnees::getY().
Referenced by AppFrame::setPositionOf().
SetSize()
void Canvas::SetSize (int width, int height)
Definition at line 227 of file Caneva.cpp.
References drawAll(), x, and y.
setTailleTexture()
void Canvas::setTailleTexture (int taille) private
Definition at line 217 of file Caneva.cpp.
References tailleTexture.
setTexture()
void Canvas::setTexture (std::string const & file) private
Definition at line 235 of file Caneva.cpp.
References getTexture(), and textures.
Referenced by addEntite().
Member Data Documentation
ground
TileMap Canvas::ground private
Definition at line 28 of file Caneva.hpp.
Referenced by drawAll(), getGround(), and loadFileIntoGround().
obj
TileMap Canvas::obj private
Definition at line 29 of file Caneva.hpp.
Referenced by drawAll(), getObj(), and loadFileIntoGround().
sky
TileMap Canvas::sky private
Definition at line 30 of file Caneva.hpp.
Referenced by drawAll(), getSky(), and loadFileIntoGround().
sprites
std::map<std::string, sf::Sprite> Canvas::sprites private
Definition at line 34 of file Caneva.hpp.
Referenced by addEntite(), drawAll(), and getSprites().
tailleTexture
int Canvas::tailleTexture private
Definition at line 35 of file Caneva.hpp.
Referenced by Canvas(), getTailleTexture(), and setTailleTexture().
textures
std::vector<sf::Texture*> Canvas::textures private
Definition at line 33 of file Caneva.hpp.
Referenced by addEntite(), getTexture(), setTexture(), and ~Canvas().
x
int Canvas::x private
Definition at line 31 of file Caneva.hpp.
Referenced by Canvas(), loadFileIntoGround(), onResize(), and SetSize().
y
int Canvas::y private
Definition at line 32 of file Caneva.hpp.
Referenced by Canvas(), loadFileIntoGround(), onResize(), and SetSize().
The documentation for this class was generated from the following files:
src/vue/Caneva.hpp
src/vue/Caneva.cpp