A Space Story: VPlayerInventaireInterface Class Reference
VPlayerInventaireInterface Class Reference abstract
#include <VPlayerInventaireInterface.hpp>
Public Member Functions
VPlayerInventaireInterface (MCoordonnees const &size)
virtual ~VPlayerInventaireInterface ()=default
virtual void addObjPlayerQuickInv (unsigned long long id, std::string name, std::string description, std::string image, int position=-1)=0
Public Member Functions inherited from VInventaireInterface
VInventaireInterface (MCoordonnees const &size)
virtual ~VInventaireInterface ()=default
virtual void addObjInv (unsigned long long id, std::string name, std::string description, std::string image, int position=-1)=0
virtual void delObjInv (unsigned long long id)=0
virtual void show (bool show=true)=0
Detailed Description
Definition at line 19 of file VPlayerInventaireInterface.hpp.
Constructor & Destructor Documentation
VPlayerInventaireInterface()
VPlayerInventaireInterface::VPlayerInventaireInterface (MCoordonnees const & size) inline
Parameters
size définie la taille de l'inventaire, et aussi le x définie la taille du quickInventaire\ Il y a donc x*(y+1) cases\
eg : x = 3, y = 2, il y a au total 3*(2+1) cases\ □□□ // inventaire □□□
□□□ // barre d'inventaire rapide
Definition at line 37 of file VPlayerInventaireInterface.hpp.
References addObjPlayerQuickInv(), and ~VPlayerInventaireInterface().
~VPlayerInventaireInterface()
virtual VPlayerInventaireInterface::~VPlayerInventaireInterface () virtual default
Referenced by VPlayerInventaireInterface().
Member Function Documentation
addObjPlayerQuickInv()
virtual void VPlayerInventaireInterface::addObjPlayerQuickInv (unsigned long long id, std::string name, std::string description, std::string image, int position = -1) pure virtual
Parameters
id id de l'objet
image image de l'objet
position la position dans l'inventaire ligne par ligne, si -1 l'objet va dans la première case disponible
Implemented in VPlayerInventory.
Referenced by VPlayerInventaireInterface().
The documentation for this class was generated from the following file:
src/vue/VPlayerInventaireInterface.hpp