A Space Story: MAssException Class Reference
MAssException Class Reference
#include <MAssException.hpp>
Public Member Functions
MAssException (std::string desc="")
virtual ~MAssException ()=default
virtual std::string what () const noexcept
Private Attributes
std::string desc
Detailed Description
Exception generique du jeu
Definition at line 26 of file MAssException.hpp.
Constructor & Destructor Documentation
MAssException()
MAssException::MAssException (std::string desc = "")
Definition at line 26 of file MAssException.cpp.
~MAssException()
virtual MAssException::~MAssException () virtual default
Member Function Documentation
what()
std::string MAssException::what () const virtual noexcept
Reimplemented in MExceptionArgumentsInvalides, MExceptionNullPtr, MExceptionEntiteDejaCreee, MExceptionEntiteInexistante, MExceptionLuaArguments, MExceptionFile, MExceptionInvalidTypeCouche, MExceptionOutOfTerrain, and MExceptionEntiteNonPresente.
Definition at line 31 of file MAssException.cpp.
References desc.
Referenced by CLua::getItem(), App::OnInit(), and CLua::testArgs().
Member Data Documentation
desc
std::string MAssException::desc private
Definition at line 30 of file MAssException.hpp.
Referenced by what().
The documentation for this class was generated from the following files:
src/model/MAssException.hpp
src/model/MAssException.cpp