A Space Story: wxImagePanelP Class Reference
wxImagePanelP Class Reference
#include <ImagePanelP.hpp>
Public Member Functions
wxImagePanelP (wxPanel *parent, wxString file, wxBitmapType format)
void paintEvent (wxPaintEvent &evt)
void paintNow ()
void OnSize (wxSizeEvent &event)
void render (wxDC &dc)
virtual void LoadImage (std::string file)
Private Attributes
wxBitmap image
wxBitmap resized
int w
int h
Detailed Description
Definition at line 12 of file ImagePanelP.hpp.
Constructor & Destructor Documentation
wxImagePanelP()
wxImagePanelP::wxImagePanelP (wxPanel * parent, wxString file, wxBitmapType format)
Definition at line 10 of file ImagePanelP.cpp.
References h, image, OnSize(), paintEvent(), and w.
Member Function Documentation
LoadImage()
void wxImagePanelP::LoadImage (std::string file) virtual
Definition at line 79 of file ImagePanelP.cpp.
References image.
Referenced by AppFrame::effacerParler(), and AppFrame::parler().
OnSize()
void wxImagePanelP::OnSize (wxSizeEvent & event)
Definition at line 72 of file ImagePanelP.cpp.
Referenced by wxImagePanelP().
paintEvent()
void wxImagePanelP::paintEvent (wxPaintEvent & evt)
Definition at line 28 of file ImagePanelP.cpp.
References render().
Referenced by wxImagePanelP().
paintNow()
void wxImagePanelP::paintNow ()
Definition at line 43 of file ImagePanelP.cpp.
References render().
Referenced by AppFrame::effacerParler(), and AppFrame::parler().
render()
void wxImagePanelP::render (wxDC & dc)
Definition at line 55 of file ImagePanelP.cpp.
References h, image, resized, and w.
Referenced by paintEvent(), and paintNow().
Member Data Documentation
h
int wxImagePanelP::h private
Definition at line 16 of file ImagePanelP.hpp.
Referenced by render(), and wxImagePanelP().
image
wxBitmap wxImagePanelP::image private
Definition at line 14 of file ImagePanelP.hpp.
Referenced by LoadImage(), render(), and wxImagePanelP().
resized
wxBitmap wxImagePanelP::resized private
Definition at line 15 of file ImagePanelP.hpp.
Referenced by render().
w
int wxImagePanelP::w private
Definition at line 16 of file ImagePanelP.hpp.
Referenced by render(), and wxImagePanelP().
The documentation for this class was generated from the following files:
src/vue/ImagePanelP.hpp
src/vue/ImagePanelP.cpp