A Space Story: MTerrain Class Reference
MTerrain Class Reference
#include <MTerrain.hpp>
Public Member Functions
MTerrain ()
virtual ~MTerrain ()
void loadCouche (std::string const &fichier, MTypeCouche const &type)
MTuile & operator() (MCoordonnees const &coord)
MTuile & operator() (int index)
MTuile & operator() (int x, int y)
std::vector< MTuile * > getAdjacentes (MTuile const &tuile)
std::vector< int > getImagesList (MTypeCouche typeCouche) const
MEntite * procheEntite (MCoordonnees coordonneeJoueur)
MCoordonnees toCoords (int index) const
Static Public Member Functions
static void loadTypes ()
static MCoordonnees getTaille ()
static void setTaille (MCoordonnees taille)
static MPartieCouche & getElement (std::string element)
static std::unordered_map< uint8_t, MPartieCouche * > & getTypeList (MTypeCouche const &typeCouche)
Static Private Member Functions
static void loadSpecificPath (std::string fichier, MTypeCouche const &type)
Private Attributes
std::vector< MTuile * > tuiles
Static Private Attributes
static std::unordered_map< std::uint8_t, MPartieCouche * > solsType
static std::unordered_map< std::uint8_t, MPartieCouche * > elementsType
static std::unordered_map< std::uint8_t, MPartieCouche * > cielsType
static MCoordonnees taille
Detailed Description
Le terrain est composée de tuile Il sert pour les organiser, initialiser\ rechercher
Definition at line 30 of file MTerrain.hpp.
Constructor & Destructor Documentation
MTerrain()
MTerrain::MTerrain ()
Definition at line 37 of file MTerrain.cpp.
References MParameters::getNbTuileX(), MParameters::getNbTuileY(), loadTypes(), and taille.
~MTerrain()
MTerrain::~MTerrain () virtual
Definition at line 44 of file MTerrain.cpp.
References tuiles.
Member Function Documentation
getAdjacentes()
std::vector< MTuile * > MTerrain::getAdjacentes (MTuile const & tuile)
Parameters
tuile
Returns
un vecteur des tuiles adjacentes (en croix sans les diagonales définie par les Mouvement)
Definition at line 264 of file MTerrain.cpp.
References MTuile::getPosition(), MouvementT::size(), and tuiles.
getElement()
MPartieCouche & MTerrain::getElement (std::string element) static
Definition at line 115 of file MTerrain.cpp.
References ELEMENT, and getTypeList().
Referenced by CLua::cppAddActionMining().
getImagesList()
std::vector< int > MTerrain::getImagesList (MTypeCouche typeCouche) const
Definition at line 287 of file MTerrain.cpp.
References MPartieCouche::getId(), and tuiles.
Referenced by CPersonnage::setEventMethods(), and CNiveau::setEventMethods().
getTaille()
MCoordonnees MTerrain::getTaille () inline static
Definition at line 84 of file MTerrain.hpp.
References taille.
getTypeList()
std::unordered_map< uint8_t, MPartieCouche * > & MTerrain::getTypeList (MTypeCouche const & typeCouche) static
Definition at line 125 of file MTerrain.cpp.
References cielsType, ELEMENT, elementsType, SOL, and solsType.
Referenced by MTuile::deletePartieCouche(), getElement(), loadCouche(), loadSpecificPath(), and MPartieCoucheElement::mine().
loadCouche()
void MTerrain::loadCouche (std::string const & fichier, MTypeCouche const & type)
Parameters
fichier le fichier de couche à charger (.data : .nbg, nvc, nsk)
type le type de couche (0,1,2 : sol, element ciel)
Definition at line 145 of file MTerrain.cpp.
References COUCHE_LOADED, getTypeList(), MCoordonnees::getX(), MCoordonnees::getY(), MouvementT::size(), SOL, taille, to_string(), toCoords(), and tuiles.
Referenced by CLua::cppLoadCouche().
loadSpecificPath()
void MTerrain::loadSpecificPath (std::string fichier, MTypeCouche const & type) static private
Definition at line 68 of file MTerrain.cpp.
References ELEMENT, and getTypeList().
Referenced by loadTypes().
loadTypes()
void MTerrain::loadTypes () static
Definition at line 56 of file MTerrain.cpp.
References CIEL, ELEMENT, MParameters::getCielsPath(), MParameters::getElementsPath(), MParameters::getSolsPath(), loadSpecificPath(), and SOL.
Referenced by MTerrain().
operator()() [1/3]
MTuile & MTerrain::operator() (MCoordonnees const & coord)
pour pouvoir faire : terrain(MCoordonnees(1,1))
Returns
la tuile spécifiée aux coordonnées coord
Exceptions
MExceptionOutOfTerrain si les coordonnées sortent du terrain
Definition at line 234 of file MTerrain.cpp.
References MCoordonnees::getX(), MCoordonnees::getY(), taille, and tuiles.
operator()() [2/3]
MTuile & MTerrain::operator() (int index)
pour pouvoir faire : terrain(15)
Returns
la tuile spécifiée a l'index index
Exceptions
MExceptionOutOfTerrain si l'index sortent du terrain
Definition at line 249 of file MTerrain.cpp.
References tuiles.
operator()() [3/3]
MTuile & MTerrain::operator() (int x, int y)
pour pouvoir faire : terrain(1,1)
Returns
la tuile spécifiée aux coordonnées (x, y)
Exceptions
MExceptionOutOfTerrain si les coordonnées sortent du terrain
Definition at line 224 of file MTerrain.cpp.
procheEntite()
MEntite* MTerrain::procheEntite (MCoordonnees coordonneeJoueur)
setTaille()
void MTerrain::setTaille (MCoordonnees taille) inline static
Definition at line 89 of file MTerrain.hpp.
References taille.
toCoords()
MCoordonnees MTerrain::toCoords (int index) const
Definition at line 63 of file MTerrain.cpp.
References MCoordonnees::getX(), and taille.
Referenced by loadCouche().
Member Data Documentation
cielsType
std::unordered_map< std::uint8_t, MPartieCouche * > MTerrain::cielsType static private
Definition at line 40 of file MTerrain.hpp.
Referenced by getTypeList().
elementsType
std::unordered_map< std::uint8_t, MPartieCouche * > MTerrain::elementsType static private
Definition at line 39 of file MTerrain.hpp.
Referenced by getTypeList().
solsType
std::unordered_map< std::uint8_t, MPartieCouche * > MTerrain::solsType static private
map pour avoir la partie couche(lu dans les fichiers *list des tuiles)
en fonction d'un index(lu dans les fichiers .n*)
Definition at line 38 of file MTerrain.hpp.
Referenced by getTypeList().
taille
MCoordonnees MTerrain::taille static private
le point qui défini la taille du terrain\ le nombre d'element sur x et sur y pour une définir x [0..3] et y [0..3] :\ MCoordonnees(4, 4)
Definition at line 47 of file MTerrain.hpp.
Referenced by getTaille(), loadCouche(), MTerrain(), operator()(), setTaille(), and toCoords().
tuiles
std::vector<MTuile*> MTerrain::tuiles private
Definition at line 49 of file MTerrain.hpp.
Referenced by getAdjacentes(), getImagesList(), loadCouche(), operator()(), and ~MTerrain().
The documentation for this class was generated from the following files:
src/model/MTerrain.hpp
src/model/MTerrain.cpp