A Space Story: MPartieCouche Class Reference
MPartieCouche Class Reference
#include <MPartieCouche.hpp>
Public Member Functions
MPartieCouche (int id, MTypeCouche type, std::string name, std::string fichierImg, float placeDispo)
MPartieCouche (MPartieCouche const &other)
virtual MPartieCouche & operator= (MPartieCouche const &other)
virtual ~MPartieCouche ()
bool isTypeOf (MTypeCouche type) const
void passageDe (MEntite *entite)
void declenchementDe (MEntite *entite)
virtual void mine (MEntite *entite, int item, MCoordonnees minedCoords)
bool isNull () const
int getId () const
void setId (int id)
MTypeCouche const & getType () const
std::string const & getName () const
std::string const & getFichierImg () const
float getPlaceDispo () const
virtual int getMiningLevel () const
void setFichierImg (std::string const &fichierImg)
void setActionDeclenchement (std::function< void(std::string entite)> actionDeclenchement)
void setActionPassage (std::function< void(std::string entite)> actionPassage)
virtual void setActionMining (std::function< void(MEntite *entite, int item, int xMined, int yMined)> actionMining)
void unSetActionDeclenchement ()
void unSetActionPassage ()
virtual void unSetActionMining ()
Static Public Attributes
static float constexpr PLACE_MAX = 1
Private Attributes
int id
MTypeCouche type
std::string name
std::string fichierImg
float placeDispo
std::function< void(std::string entite)> actionPassage
std::function< void(std::string entite)> actionDeclenchement
Detailed Description
Definition at line 31 of file MPartieCouche.hpp.
Constructor & Destructor Documentation
MPartieCouche() [1/2]
MPartieCouche::MPartieCouche (int id, MTypeCouche type, std::string name, std::string fichierImg, float placeDispo)
Definition at line 26 of file MPartieCouche.cpp.
MPartieCouche() [2/2]
MPartieCouche::MPartieCouche (MPartieCouche const & other)
Definition at line 33 of file MPartieCouche.cpp.
~MPartieCouche()
MPartieCouche::~MPartieCouche () virtual
Definition at line 52 of file MPartieCouche.cpp.
Member Function Documentation
declenchementDe()
void MPartieCouche::declenchementDe (MEntite * entite)
Definition at line 73 of file MPartieCouche.cpp.
References actionDeclenchement, MEntite::getNom(), and MThreads::parallelize().
Referenced by MTuile::interagirTuile().
getFichierImg()
std::string const & MPartieCouche::getFichierImg () const
Definition at line 104 of file MPartieCouche.cpp.
References fichierImg.
Referenced by MPartieCoucheElement::mine().
getId()
int MPartieCouche::getId () const inline
Definition at line 109 of file MPartieCouche.hpp.
Referenced by MTerrain::getImagesList(), and MPartieCoucheElement::mine().
getMiningLevel()
int MPartieCouche::getMiningLevel () const virtual
Reimplemented in MPartieCoucheElement.
Definition at line 114 of file MPartieCouche.cpp.
Referenced by MTuile::mine().
getName()
std::string const & MPartieCouche::getName () const
Definition at line 99 of file MPartieCouche.cpp.
References name.
Referenced by MTuile::addInventaire(), and MExceptionEntiteNonPresente::what().
getPlaceDispo()
float MPartieCouche::getPlaceDispo () const
Definition at line 109 of file MPartieCouche.cpp.
References placeDispo.
getType()
MTypeCouche const & MPartieCouche::getType () const
Definition at line 94 of file MPartieCouche.cpp.
References type.
Referenced by isTypeOf(), MPartieCoucheElement::mine(), and MTuile::setPartieCouche().
isNull()
bool MPartieCouche::isNull () const
Definition at line 86 of file MPartieCouche.cpp.
Referenced by MTuile::hasPartieCouche().
isTypeOf()
bool MPartieCouche::isTypeOf (MTypeCouche type) const
Definition at line 60 of file MPartieCouche.cpp.
References getType(), and type.
Referenced by MTuile::setPartieCouche().
mine()
void MPartieCouche::mine (MEntite * entite, int item, MCoordonnees minedCoords) virtual
Reimplemented in MPartieCoucheElement.
Definition at line 81 of file MPartieCouche.cpp.
Referenced by MTuile::mine().
operator=()
MPartieCouche & MPartieCouche::operator= (MPartieCouche const & other) virtual
Definition at line 40 of file MPartieCouche.cpp.
References actionDeclenchement, actionPassage, fichierImg, id, name, placeDispo, and type.
Referenced by MPartieCoucheElement::operator=().
passageDe()
void MPartieCouche::passageDe (MEntite * entite)
Definition at line 65 of file MPartieCouche.cpp.
References actionPassage, MEntite::getNom(), and MThreads::parallelize().
Referenced by MTuile::placeEntite().
setActionDeclenchement()
void MPartieCouche::setActionDeclenchement (std::function< void(std::string entite)> actionDeclenchement) inline
Definition at line 119 of file MPartieCouche.hpp.
setActionMining()
void MPartieCouche::setActionMining (std::function< void(MEntite *entite, int item, int xMined, int yMined)> actionMining) virtual
Reimplemented in MPartieCoucheElement.
Definition at line 119 of file MPartieCouche.cpp.
Referenced by CLua::cppAddActionMining().
setActionPassage()
void MPartieCouche::setActionPassage (std::function< void(std::string entite)> actionPassage) inline
Definition at line 125 of file MPartieCouche.hpp.
Referenced by CLua::cppAddActionPassage().
setFichierImg()
void MPartieCouche::setFichierImg (std::string const & fichierImg) inline
Definition at line 114 of file MPartieCouche.hpp.
Referenced by MPartieCoucheElement::mine().
setId()
void MPartieCouche::setId (int id) inline
Definition at line 136 of file MPartieCouche.hpp.
Referenced by MPartieCoucheElement::mine().
unSetActionDeclenchement()
void MPartieCouche::unSetActionDeclenchement () inline
Definition at line 131 of file MPartieCouche.hpp.
unSetActionMining()
void MPartieCouche::unSetActionMining () virtual
Reimplemented in MPartieCoucheElement.
Definition at line 125 of file MPartieCouche.cpp.
unSetActionPassage()
void MPartieCouche::unSetActionPassage () inline
Definition at line 141 of file MPartieCouche.hpp.
Member Data Documentation
actionDeclenchement
std::function<void(std::string entite)> MPartieCouche::actionDeclenchement private
action set by lua
See also
CLua::addActionDeclenchement
Definition at line 57 of file MPartieCouche.hpp.
Referenced by declenchementDe(), and operator=().
actionPassage
std::function<void(std::string entite)> MPartieCouche::actionPassage private
action set by lua
See also
CLua::addActionPassage
Definition at line 52 of file MPartieCouche.hpp.
Referenced by operator=(), and passageDe().
fichierImg
std::string MPartieCouche::fichierImg private
Definition at line 45 of file MPartieCouche.hpp.
Referenced by getFichierImg(), and operator=().
id
int MPartieCouche::id private
l'id de couleur indexée définie par gimp pour le lien avec une image définie dans la *List (*=sol|element|ciel)
Definition at line 42 of file MPartieCouche.hpp.
Referenced by operator=().
name
std::string MPartieCouche::name private
Definition at line 44 of file MPartieCouche.hpp.
Referenced by getName(), and operator=().
PLACE_MAX
float constexpr MPartieCouche::PLACE_MAX = 1 static
Definition at line 35 of file MPartieCouche.hpp.
Referenced by MTuile::getPlaceDispoOn().
placeDispo
float MPartieCouche::placeDispo private
Definition at line 46 of file MPartieCouche.hpp.
Referenced by getPlaceDispo(), and operator=().
type
MTypeCouche MPartieCouche::type private
Definition at line 43 of file MPartieCouche.hpp.
Referenced by getType(), isTypeOf(), and operator=().
The documentation for this class was generated from the following files:
src/model/MPartieCouche.hpp
src/model/MPartieCouche.cpp