A Space Story: src/model/MPartieCouche.hpp File Reference
MPartieCouche.hpp File Reference
TODO complete.
#include "MEntite.hpp"
#include <array>
#include <exception>
#include <functional>
#include <string>
Classes
class MPartieCouche
Enumerations
enum MTypeCouche { MTypeCouche::SOL, MTypeCouche::ELEMENT, MTypeCouche::CIEL, MTypeCouche::SIZE }
Functions
std::string to_string (MTypeCouche coucheT)
Detailed Description
TODO complete.
Early optimization is the root of all evil
Date
23 nov. 2017
Author
FederAndInk
Definition in file MPartieCouche.hpp.
Enumeration Type Documentation
MTypeCouche
enum MTypeCouche strong
Enumerator
SOL
ELEMENT
CIEL
SIZE
Definition at line 20 of file MPartieCouche.hpp.
Function Documentation
to_string()
std::string to_string (MTypeCouche coucheT)
Definition at line 130 of file MPartieCouche.cpp.
Referenced by CLua::cppAddActionDeclenchement(), MParameters::getTextureFor(), MTerrain::loadCouche(), MExceptionLuaArguments::MExceptionLuaArguments(), Canvas::onCursor(), MEntite::setTaille(), MCoordonnees::str(), CLua::testArgs(), MExceptionOutOfTerrain::what(), and MExceptionInvalidTypeCouche::what().