A Space Story: AppFrame Struct Reference
AppFrame Struct Reference
#include <AppFrame.hpp>
Public Member Functions
AppFrame (wxString const &title, wxPoint const &pos, wxSize const &size, int tailleTexture, MCoordonnees taille=MCoordonnees(10, 8))
virtual ~AppFrame ()
void loadFileIntoGround (int const *idList, std::string texture, MTypeCouche level, int tailleTexture) override
void addEntite (std::string name, std::string file) override
void move (std::string entityName, MCoordonnees const &offset, Mouvement direction) override
void setPositionOf (std::string entityName, MCoordonnees const &offset, Mouvement direction) override
void showEnigma (std::string title, std::string file, std::string textInside)
wxPanel * getPanel ()
void parler (std::string entityTexture, std::string parole)
void effacerParler ()
Public Member Functions inherited from AppFrameInterface
AppFrameInterface ()=default
virtual ~AppFrameInterface ()=default
Public Attributes
wxTextCtrl * cursorloc
wxTextCtrl * dialogBox
wxImagePanelP * persoDireImage
std::mutex waitNextParler
Private Member Functions
Canvas * getCaneva ()
void onFocus (wxFocusEvent &event)
void onKey (wxKeyEvent &event)
void onResize (wxSizeEvent &event)
void onNext (wxCommandEvent &event)
Private Attributes
Canvas * _canvas
wxPanel * _panel2
MCoordonnees tailleInventory
Detailed Description
La racine de la vue (application)
Definition at line 19 of file AppFrame.hpp.
Constructor & Destructor Documentation
AppFrame()
AppFrame::AppFrame (wxString const & title, wxPoint const & pos, wxSize const & size, int tailleTexture, MCoordonnees taille = MCoordonnees(10, 8))
Definition at line 32 of file AppFrame.cpp.
References _canvas, _panel2, cursorloc, dialogBox, EXIT, MParameters::getRootPath(), onKey(), onNext(), and persoDireImage.
~AppFrame()
AppFrame::~AppFrame () virtual
Definition at line 182 of file AppFrame.cpp.
References _canvas, and _panel2.
Member Function Documentation
addEntite()
void AppFrame::addEntite (std::string name, std::string file) override virtual
Implements AppFrameInterface.
Definition at line 126 of file AppFrame.cpp.
References Canvas::addEntite(), and getCaneva().
effacerParler()
void AppFrame::effacerParler ()
Definition at line 211 of file AppFrame.cpp.
References dialogBox, MParameters::getRootPath(), wxImagePanelP::LoadImage(), wxImagePanelP::paintNow(), and persoDireImage.
Referenced by onNext().
getCaneva()
Canvas * AppFrame::getCaneva () private
Definition at line 131 of file AppFrame.cpp.
References _canvas.
Referenced by addEntite(), and loadFileIntoGround().
getPanel()
wxPanel * AppFrame::getPanel ()
Definition at line 160 of file AppFrame.cpp.
References _panel2.
loadFileIntoGround()
void AppFrame::loadFileIntoGround (int const * idList, std::string texture, MTypeCouche level, int tailleTexture) override virtual
Implements AppFrameInterface.
Definition at line 120 of file AppFrame.cpp.
References getCaneva(), and Canvas::loadFileIntoGround().
move()
void AppFrame::move (std::string entityName, MCoordonnees const & offset, Mouvement direction) override virtual
Implements AppFrameInterface.
Definition at line 165 of file AppFrame.cpp.
References _canvas, and Canvas::move().
onFocus()
void AppFrame::onFocus (wxFocusEvent & event) private
Definition at line 156 of file AppFrame.cpp.
onKey()
void AppFrame::onKey (wxKeyEvent & event) private
Definition at line 140 of file AppFrame.cpp.
References KEY_PRESSED, and waitNextParler.
Referenced by AppFrame().
onNext()
void AppFrame::onNext (wxCommandEvent & event) private
Definition at line 188 of file AppFrame.cpp.
References effacerParler(), and waitNextParler.
Referenced by AppFrame().
onResize()
void AppFrame::onResize (wxSizeEvent & event) private
Definition at line 136 of file AppFrame.cpp.
parler()
void AppFrame::parler (std::string entityTexture, std::string parole) virtual
Implements AppFrameInterface.
Definition at line 196 of file AppFrame.cpp.
References dialogBox, wxImagePanelP::LoadImage(), wxImagePanelP::paintNow(), persoDireImage, and waitNextParler.
setPositionOf()
void AppFrame::setPositionOf (std::string entityName, MCoordonnees const & offset, Mouvement direction) override virtual
Implements AppFrameInterface.
Definition at line 170 of file AppFrame.cpp.
References _canvas, and Canvas::setPositionOf().
showEnigma()
void AppFrame::showEnigma (std::string title, std::string file, std::string textInside)
Definition at line 176 of file AppFrame.cpp.
Member Data Documentation
_canvas
Canvas* AppFrame::_canvas private
Definition at line 50 of file AppFrame.hpp.
Referenced by AppFrame(), getCaneva(), move(), setPositionOf(), and ~AppFrame().
_panel2
wxPanel* AppFrame::_panel2 private
Definition at line 51 of file AppFrame.hpp.
Referenced by AppFrame(), getPanel(), and ~AppFrame().
cursorloc
wxTextCtrl* AppFrame::cursorloc
Definition at line 54 of file AppFrame.hpp.
Referenced by AppFrame().
dialogBox
wxTextCtrl* AppFrame::dialogBox
Definition at line 55 of file AppFrame.hpp.
Referenced by AppFrame(), effacerParler(), and parler().
persoDireImage
wxImagePanelP* AppFrame::persoDireImage
Definition at line 56 of file AppFrame.hpp.
Referenced by AppFrame(), effacerParler(), and parler().
tailleInventory
MCoordonnees AppFrame::tailleInventory private
Definition at line 52 of file AppFrame.hpp.
waitNextParler
std::mutex AppFrame::waitNextParler
Definition at line 58 of file AppFrame.hpp.
Referenced by onKey(), onNext(), and parler().
The documentation for this struct was generated from the following files:
src/vue/AppFrame.hpp
src/vue/AppFrame.cpp