A Space Story: src/vue/VPrimitif.cpp File Reference
VPrimitif.cpp File Reference
#include "VPrimitif.hpp"
#include "../model/MEvents.hpp"
#include <bits/exception.h>
#include <cstdlib>
#include <ios>
#include <iostream>
#include <limits>
Functions
void clear (istream &in)
void clearScreen ()
Function Documentation
clear()
void clear (istream & in)
Definition at line 55 of file VPrimitif.cpp.
Referenced by Canvas::drawAll(), and VPrimitif::sendInput().
clearScreen()
void clearScreen ()
Definition at line 60 of file VPrimitif.cpp.
Referenced by VPrimitif::show().